// Code generated by ent, DO NOT EDIT.

package integrationupdate

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/pdlc-os/fabric/pkg/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldLTE(FieldID, id))
}

// Integration applies equality check predicate on the "integration" field. It's identical to IntegrationEQ.
func Integration(v string) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldEQ(FieldIntegration, v))
}

// Detail applies equality check predicate on the "detail" field. It's identical to DetailEQ.
func Detail(v string) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldEQ(FieldDetail, v))
}

// NewVersion applies equality check predicate on the "new_version" field. It's identical to NewVersionEQ.
func NewVersion(v string) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldEQ(FieldNewVersion, v))
}

// RequestedBy applies equality check predicate on the "requested_by" field. It's identical to RequestedByEQ.
func RequestedBy(v string) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldEQ(FieldRequestedBy, v))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldEQ(FieldUpdateTime, v))
}

// IntegrationEQ applies the EQ predicate on the "integration" field.
func IntegrationEQ(v string) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldEQ(FieldIntegration, v))
}

// IntegrationNEQ applies the NEQ predicate on the "integration" field.
func IntegrationNEQ(v string) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldNEQ(FieldIntegration, v))
}

// IntegrationIn applies the In predicate on the "integration" field.
func IntegrationIn(vs ...string) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldIn(FieldIntegration, vs...))
}

// IntegrationNotIn applies the NotIn predicate on the "integration" field.
func IntegrationNotIn(vs ...string) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldNotIn(FieldIntegration, vs...))
}

// IntegrationGT applies the GT predicate on the "integration" field.
func IntegrationGT(v string) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldGT(FieldIntegration, v))
}

// IntegrationGTE applies the GTE predicate on the "integration" field.
func IntegrationGTE(v string) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldGTE(FieldIntegration, v))
}

// IntegrationLT applies the LT predicate on the "integration" field.
func IntegrationLT(v string) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldLT(FieldIntegration, v))
}

// IntegrationLTE applies the LTE predicate on the "integration" field.
func IntegrationLTE(v string) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldLTE(FieldIntegration, v))
}

// IntegrationContains applies the Contains predicate on the "integration" field.
func IntegrationContains(v string) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldContains(FieldIntegration, v))
}

// IntegrationHasPrefix applies the HasPrefix predicate on the "integration" field.
func IntegrationHasPrefix(v string) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldHasPrefix(FieldIntegration, v))
}

// IntegrationHasSuffix applies the HasSuffix predicate on the "integration" field.
func IntegrationHasSuffix(v string) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldHasSuffix(FieldIntegration, v))
}

// IntegrationEqualFold applies the EqualFold predicate on the "integration" field.
func IntegrationEqualFold(v string) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldEqualFold(FieldIntegration, v))
}

// IntegrationContainsFold applies the ContainsFold predicate on the "integration" field.
func IntegrationContainsFold(v string) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldContainsFold(FieldIntegration, v))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v State) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v State) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldNEQ(FieldState, v))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...State) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldIn(FieldState, vs...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...State) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldNotIn(FieldState, vs...))
}

// DetailEQ applies the EQ predicate on the "detail" field.
func DetailEQ(v string) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldEQ(FieldDetail, v))
}

// DetailNEQ applies the NEQ predicate on the "detail" field.
func DetailNEQ(v string) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldNEQ(FieldDetail, v))
}

// DetailIn applies the In predicate on the "detail" field.
func DetailIn(vs ...string) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldIn(FieldDetail, vs...))
}

// DetailNotIn applies the NotIn predicate on the "detail" field.
func DetailNotIn(vs ...string) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldNotIn(FieldDetail, vs...))
}

// DetailGT applies the GT predicate on the "detail" field.
func DetailGT(v string) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldGT(FieldDetail, v))
}

// DetailGTE applies the GTE predicate on the "detail" field.
func DetailGTE(v string) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldGTE(FieldDetail, v))
}

// DetailLT applies the LT predicate on the "detail" field.
func DetailLT(v string) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldLT(FieldDetail, v))
}

// DetailLTE applies the LTE predicate on the "detail" field.
func DetailLTE(v string) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldLTE(FieldDetail, v))
}

// DetailContains applies the Contains predicate on the "detail" field.
func DetailContains(v string) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldContains(FieldDetail, v))
}

// DetailHasPrefix applies the HasPrefix predicate on the "detail" field.
func DetailHasPrefix(v string) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldHasPrefix(FieldDetail, v))
}

// DetailHasSuffix applies the HasSuffix predicate on the "detail" field.
func DetailHasSuffix(v string) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldHasSuffix(FieldDetail, v))
}

// DetailIsNil applies the IsNil predicate on the "detail" field.
func DetailIsNil() predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldIsNull(FieldDetail))
}

// DetailNotNil applies the NotNil predicate on the "detail" field.
func DetailNotNil() predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldNotNull(FieldDetail))
}

// DetailEqualFold applies the EqualFold predicate on the "detail" field.
func DetailEqualFold(v string) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldEqualFold(FieldDetail, v))
}

// DetailContainsFold applies the ContainsFold predicate on the "detail" field.
func DetailContainsFold(v string) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldContainsFold(FieldDetail, v))
}

// NewVersionEQ applies the EQ predicate on the "new_version" field.
func NewVersionEQ(v string) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldEQ(FieldNewVersion, v))
}

// NewVersionNEQ applies the NEQ predicate on the "new_version" field.
func NewVersionNEQ(v string) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldNEQ(FieldNewVersion, v))
}

// NewVersionIn applies the In predicate on the "new_version" field.
func NewVersionIn(vs ...string) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldIn(FieldNewVersion, vs...))
}

// NewVersionNotIn applies the NotIn predicate on the "new_version" field.
func NewVersionNotIn(vs ...string) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldNotIn(FieldNewVersion, vs...))
}

// NewVersionGT applies the GT predicate on the "new_version" field.
func NewVersionGT(v string) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldGT(FieldNewVersion, v))
}

// NewVersionGTE applies the GTE predicate on the "new_version" field.
func NewVersionGTE(v string) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldGTE(FieldNewVersion, v))
}

// NewVersionLT applies the LT predicate on the "new_version" field.
func NewVersionLT(v string) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldLT(FieldNewVersion, v))
}

// NewVersionLTE applies the LTE predicate on the "new_version" field.
func NewVersionLTE(v string) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldLTE(FieldNewVersion, v))
}

// NewVersionContains applies the Contains predicate on the "new_version" field.
func NewVersionContains(v string) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldContains(FieldNewVersion, v))
}

// NewVersionHasPrefix applies the HasPrefix predicate on the "new_version" field.
func NewVersionHasPrefix(v string) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldHasPrefix(FieldNewVersion, v))
}

// NewVersionHasSuffix applies the HasSuffix predicate on the "new_version" field.
func NewVersionHasSuffix(v string) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldHasSuffix(FieldNewVersion, v))
}

// NewVersionIsNil applies the IsNil predicate on the "new_version" field.
func NewVersionIsNil() predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldIsNull(FieldNewVersion))
}

// NewVersionNotNil applies the NotNil predicate on the "new_version" field.
func NewVersionNotNil() predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldNotNull(FieldNewVersion))
}

// NewVersionEqualFold applies the EqualFold predicate on the "new_version" field.
func NewVersionEqualFold(v string) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldEqualFold(FieldNewVersion, v))
}

// NewVersionContainsFold applies the ContainsFold predicate on the "new_version" field.
func NewVersionContainsFold(v string) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldContainsFold(FieldNewVersion, v))
}

// RequestedByEQ applies the EQ predicate on the "requested_by" field.
func RequestedByEQ(v string) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldEQ(FieldRequestedBy, v))
}

// RequestedByNEQ applies the NEQ predicate on the "requested_by" field.
func RequestedByNEQ(v string) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldNEQ(FieldRequestedBy, v))
}

// RequestedByIn applies the In predicate on the "requested_by" field.
func RequestedByIn(vs ...string) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldIn(FieldRequestedBy, vs...))
}

// RequestedByNotIn applies the NotIn predicate on the "requested_by" field.
func RequestedByNotIn(vs ...string) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldNotIn(FieldRequestedBy, vs...))
}

// RequestedByGT applies the GT predicate on the "requested_by" field.
func RequestedByGT(v string) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldGT(FieldRequestedBy, v))
}

// RequestedByGTE applies the GTE predicate on the "requested_by" field.
func RequestedByGTE(v string) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldGTE(FieldRequestedBy, v))
}

// RequestedByLT applies the LT predicate on the "requested_by" field.
func RequestedByLT(v string) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldLT(FieldRequestedBy, v))
}

// RequestedByLTE applies the LTE predicate on the "requested_by" field.
func RequestedByLTE(v string) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldLTE(FieldRequestedBy, v))
}

// RequestedByContains applies the Contains predicate on the "requested_by" field.
func RequestedByContains(v string) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldContains(FieldRequestedBy, v))
}

// RequestedByHasPrefix applies the HasPrefix predicate on the "requested_by" field.
func RequestedByHasPrefix(v string) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldHasPrefix(FieldRequestedBy, v))
}

// RequestedByHasSuffix applies the HasSuffix predicate on the "requested_by" field.
func RequestedByHasSuffix(v string) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldHasSuffix(FieldRequestedBy, v))
}

// RequestedByIsNil applies the IsNil predicate on the "requested_by" field.
func RequestedByIsNil() predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldIsNull(FieldRequestedBy))
}

// RequestedByNotNil applies the NotNil predicate on the "requested_by" field.
func RequestedByNotNil() predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldNotNull(FieldRequestedBy))
}

// RequestedByEqualFold applies the EqualFold predicate on the "requested_by" field.
func RequestedByEqualFold(v string) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldEqualFold(FieldRequestedBy, v))
}

// RequestedByContainsFold applies the ContainsFold predicate on the "requested_by" field.
func RequestedByContainsFold(v string) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldContainsFold(FieldRequestedBy, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.FieldLTE(FieldUpdateTime, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.IntegrationUpdate) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.IntegrationUpdate) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.IntegrationUpdate) predicate.IntegrationUpdate {
	return predicate.IntegrationUpdate(sql.NotPredicates(p))
}
