// Code generated by ent, DO NOT EDIT.

package integrationconfig

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/pdlc-os/fabric/pkg/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldLTE(FieldID, id))
}

// Integration applies equality check predicate on the "integration" field. It's identical to IntegrationEQ.
func Integration(v string) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldEQ(FieldIntegration, v))
}

// Config applies equality check predicate on the "config" field. It's identical to ConfigEQ.
func Config(v string) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldEQ(FieldConfig, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldEQ(FieldEnabled, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v string) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldEQ(FieldUpdatedBy, v))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldEQ(FieldUpdateTime, v))
}

// IntegrationEQ applies the EQ predicate on the "integration" field.
func IntegrationEQ(v string) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldEQ(FieldIntegration, v))
}

// IntegrationNEQ applies the NEQ predicate on the "integration" field.
func IntegrationNEQ(v string) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldNEQ(FieldIntegration, v))
}

// IntegrationIn applies the In predicate on the "integration" field.
func IntegrationIn(vs ...string) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldIn(FieldIntegration, vs...))
}

// IntegrationNotIn applies the NotIn predicate on the "integration" field.
func IntegrationNotIn(vs ...string) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldNotIn(FieldIntegration, vs...))
}

// IntegrationGT applies the GT predicate on the "integration" field.
func IntegrationGT(v string) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldGT(FieldIntegration, v))
}

// IntegrationGTE applies the GTE predicate on the "integration" field.
func IntegrationGTE(v string) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldGTE(FieldIntegration, v))
}

// IntegrationLT applies the LT predicate on the "integration" field.
func IntegrationLT(v string) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldLT(FieldIntegration, v))
}

// IntegrationLTE applies the LTE predicate on the "integration" field.
func IntegrationLTE(v string) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldLTE(FieldIntegration, v))
}

// IntegrationContains applies the Contains predicate on the "integration" field.
func IntegrationContains(v string) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldContains(FieldIntegration, v))
}

// IntegrationHasPrefix applies the HasPrefix predicate on the "integration" field.
func IntegrationHasPrefix(v string) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldHasPrefix(FieldIntegration, v))
}

// IntegrationHasSuffix applies the HasSuffix predicate on the "integration" field.
func IntegrationHasSuffix(v string) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldHasSuffix(FieldIntegration, v))
}

// IntegrationEqualFold applies the EqualFold predicate on the "integration" field.
func IntegrationEqualFold(v string) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldEqualFold(FieldIntegration, v))
}

// IntegrationContainsFold applies the ContainsFold predicate on the "integration" field.
func IntegrationContainsFold(v string) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldContainsFold(FieldIntegration, v))
}

// ConfigEQ applies the EQ predicate on the "config" field.
func ConfigEQ(v string) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldEQ(FieldConfig, v))
}

// ConfigNEQ applies the NEQ predicate on the "config" field.
func ConfigNEQ(v string) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldNEQ(FieldConfig, v))
}

// ConfigIn applies the In predicate on the "config" field.
func ConfigIn(vs ...string) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldIn(FieldConfig, vs...))
}

// ConfigNotIn applies the NotIn predicate on the "config" field.
func ConfigNotIn(vs ...string) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldNotIn(FieldConfig, vs...))
}

// ConfigGT applies the GT predicate on the "config" field.
func ConfigGT(v string) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldGT(FieldConfig, v))
}

// ConfigGTE applies the GTE predicate on the "config" field.
func ConfigGTE(v string) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldGTE(FieldConfig, v))
}

// ConfigLT applies the LT predicate on the "config" field.
func ConfigLT(v string) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldLT(FieldConfig, v))
}

// ConfigLTE applies the LTE predicate on the "config" field.
func ConfigLTE(v string) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldLTE(FieldConfig, v))
}

// ConfigContains applies the Contains predicate on the "config" field.
func ConfigContains(v string) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldContains(FieldConfig, v))
}

// ConfigHasPrefix applies the HasPrefix predicate on the "config" field.
func ConfigHasPrefix(v string) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldHasPrefix(FieldConfig, v))
}

// ConfigHasSuffix applies the HasSuffix predicate on the "config" field.
func ConfigHasSuffix(v string) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldHasSuffix(FieldConfig, v))
}

// ConfigEqualFold applies the EqualFold predicate on the "config" field.
func ConfigEqualFold(v string) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldEqualFold(FieldConfig, v))
}

// ConfigContainsFold applies the ContainsFold predicate on the "config" field.
func ConfigContainsFold(v string) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldContainsFold(FieldConfig, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldNEQ(FieldEnabled, v))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v string) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v string) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...string) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...string) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v string) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v string) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v string) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v string) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByContains applies the Contains predicate on the "updated_by" field.
func UpdatedByContains(v string) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldContains(FieldUpdatedBy, v))
}

// UpdatedByHasPrefix applies the HasPrefix predicate on the "updated_by" field.
func UpdatedByHasPrefix(v string) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldHasPrefix(FieldUpdatedBy, v))
}

// UpdatedByHasSuffix applies the HasSuffix predicate on the "updated_by" field.
func UpdatedByHasSuffix(v string) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldHasSuffix(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldNotNull(FieldUpdatedBy))
}

// UpdatedByEqualFold applies the EqualFold predicate on the "updated_by" field.
func UpdatedByEqualFold(v string) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldEqualFold(FieldUpdatedBy, v))
}

// UpdatedByContainsFold applies the ContainsFold predicate on the "updated_by" field.
func UpdatedByContainsFold(v string) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldContainsFold(FieldUpdatedBy, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.FieldLTE(FieldUpdateTime, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.IntegrationConfig) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.IntegrationConfig) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.IntegrationConfig) predicate.IntegrationConfig {
	return predicate.IntegrationConfig(sql.NotPredicates(p))
}
