// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/pdlc-os/fabric/pkg/ent/discordpendinglink"
	"github.com/pdlc-os/fabric/pkg/ent/predicate"
)

// DiscordPendingLinkUpdate is the builder for updating DiscordPendingLink entities.
type DiscordPendingLinkUpdate struct {
	config
	hooks    []Hook
	mutation *DiscordPendingLinkMutation
}

// Where appends a list predicates to the DiscordPendingLinkUpdate builder.
func (_u *DiscordPendingLinkUpdate) Where(ps ...predicate.DiscordPendingLink) *DiscordPendingLinkUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCode sets the "code" field.
func (_u *DiscordPendingLinkUpdate) SetCode(v string) *DiscordPendingLinkUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *DiscordPendingLinkUpdate) SetNillableCode(v *string) *DiscordPendingLinkUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetDiscordUserID sets the "discord_user_id" field.
func (_u *DiscordPendingLinkUpdate) SetDiscordUserID(v string) *DiscordPendingLinkUpdate {
	_u.mutation.SetDiscordUserID(v)
	return _u
}

// SetNillableDiscordUserID sets the "discord_user_id" field if the given value is not nil.
func (_u *DiscordPendingLinkUpdate) SetNillableDiscordUserID(v *string) *DiscordPendingLinkUpdate {
	if v != nil {
		_u.SetDiscordUserID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *DiscordPendingLinkUpdate) SetStatus(v string) *DiscordPendingLinkUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DiscordPendingLinkUpdate) SetNillableStatus(v *string) *DiscordPendingLinkUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *DiscordPendingLinkUpdate) SetUserID(v string) *DiscordPendingLinkUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *DiscordPendingLinkUpdate) SetNillableUserID(v *string) *DiscordPendingLinkUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUserEmail sets the "user_email" field.
func (_u *DiscordPendingLinkUpdate) SetUserEmail(v string) *DiscordPendingLinkUpdate {
	_u.mutation.SetUserEmail(v)
	return _u
}

// SetNillableUserEmail sets the "user_email" field if the given value is not nil.
func (_u *DiscordPendingLinkUpdate) SetNillableUserEmail(v *string) *DiscordPendingLinkUpdate {
	if v != nil {
		_u.SetUserEmail(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *DiscordPendingLinkUpdate) SetExpiresAt(v time.Time) *DiscordPendingLinkUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *DiscordPendingLinkUpdate) SetNillableExpiresAt(v *time.Time) *DiscordPendingLinkUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// Mutation returns the DiscordPendingLinkMutation object of the builder.
func (_u *DiscordPendingLinkUpdate) Mutation() *DiscordPendingLinkMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DiscordPendingLinkUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DiscordPendingLinkUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DiscordPendingLinkUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DiscordPendingLinkUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DiscordPendingLinkUpdate) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := discordpendinglink.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "DiscordPendingLink.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DiscordUserID(); ok {
		if err := discordpendinglink.DiscordUserIDValidator(v); err != nil {
			return &ValidationError{Name: "discord_user_id", err: fmt.Errorf(`ent: validator failed for field "DiscordPendingLink.discord_user_id": %w`, err)}
		}
	}
	return nil
}

func (_u *DiscordPendingLinkUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(discordpendinglink.Table, discordpendinglink.Columns, sqlgraph.NewFieldSpec(discordpendinglink.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(discordpendinglink.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.DiscordUserID(); ok {
		_spec.SetField(discordpendinglink.FieldDiscordUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(discordpendinglink.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(discordpendinglink.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserEmail(); ok {
		_spec.SetField(discordpendinglink.FieldUserEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(discordpendinglink.FieldExpiresAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{discordpendinglink.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DiscordPendingLinkUpdateOne is the builder for updating a single DiscordPendingLink entity.
type DiscordPendingLinkUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DiscordPendingLinkMutation
}

// SetCode sets the "code" field.
func (_u *DiscordPendingLinkUpdateOne) SetCode(v string) *DiscordPendingLinkUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *DiscordPendingLinkUpdateOne) SetNillableCode(v *string) *DiscordPendingLinkUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetDiscordUserID sets the "discord_user_id" field.
func (_u *DiscordPendingLinkUpdateOne) SetDiscordUserID(v string) *DiscordPendingLinkUpdateOne {
	_u.mutation.SetDiscordUserID(v)
	return _u
}

// SetNillableDiscordUserID sets the "discord_user_id" field if the given value is not nil.
func (_u *DiscordPendingLinkUpdateOne) SetNillableDiscordUserID(v *string) *DiscordPendingLinkUpdateOne {
	if v != nil {
		_u.SetDiscordUserID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *DiscordPendingLinkUpdateOne) SetStatus(v string) *DiscordPendingLinkUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DiscordPendingLinkUpdateOne) SetNillableStatus(v *string) *DiscordPendingLinkUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *DiscordPendingLinkUpdateOne) SetUserID(v string) *DiscordPendingLinkUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *DiscordPendingLinkUpdateOne) SetNillableUserID(v *string) *DiscordPendingLinkUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUserEmail sets the "user_email" field.
func (_u *DiscordPendingLinkUpdateOne) SetUserEmail(v string) *DiscordPendingLinkUpdateOne {
	_u.mutation.SetUserEmail(v)
	return _u
}

// SetNillableUserEmail sets the "user_email" field if the given value is not nil.
func (_u *DiscordPendingLinkUpdateOne) SetNillableUserEmail(v *string) *DiscordPendingLinkUpdateOne {
	if v != nil {
		_u.SetUserEmail(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *DiscordPendingLinkUpdateOne) SetExpiresAt(v time.Time) *DiscordPendingLinkUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *DiscordPendingLinkUpdateOne) SetNillableExpiresAt(v *time.Time) *DiscordPendingLinkUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// Mutation returns the DiscordPendingLinkMutation object of the builder.
func (_u *DiscordPendingLinkUpdateOne) Mutation() *DiscordPendingLinkMutation {
	return _u.mutation
}

// Where appends a list predicates to the DiscordPendingLinkUpdate builder.
func (_u *DiscordPendingLinkUpdateOne) Where(ps ...predicate.DiscordPendingLink) *DiscordPendingLinkUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DiscordPendingLinkUpdateOne) Select(field string, fields ...string) *DiscordPendingLinkUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DiscordPendingLink entity.
func (_u *DiscordPendingLinkUpdateOne) Save(ctx context.Context) (*DiscordPendingLink, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DiscordPendingLinkUpdateOne) SaveX(ctx context.Context) *DiscordPendingLink {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DiscordPendingLinkUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DiscordPendingLinkUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DiscordPendingLinkUpdateOne) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := discordpendinglink.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "DiscordPendingLink.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DiscordUserID(); ok {
		if err := discordpendinglink.DiscordUserIDValidator(v); err != nil {
			return &ValidationError{Name: "discord_user_id", err: fmt.Errorf(`ent: validator failed for field "DiscordPendingLink.discord_user_id": %w`, err)}
		}
	}
	return nil
}

func (_u *DiscordPendingLinkUpdateOne) sqlSave(ctx context.Context) (_node *DiscordPendingLink, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(discordpendinglink.Table, discordpendinglink.Columns, sqlgraph.NewFieldSpec(discordpendinglink.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DiscordPendingLink.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, discordpendinglink.FieldID)
		for _, f := range fields {
			if !discordpendinglink.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != discordpendinglink.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(discordpendinglink.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.DiscordUserID(); ok {
		_spec.SetField(discordpendinglink.FieldDiscordUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(discordpendinglink.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(discordpendinglink.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserEmail(); ok {
		_spec.SetField(discordpendinglink.FieldUserEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(discordpendinglink.FieldExpiresAt, field.TypeTime, value)
	}
	_node = &DiscordPendingLink{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{discordpendinglink.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
