// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/pdlc-os/fabric/pkg/ent/discordpendinglink"
)

// DiscordPendingLinkCreate is the builder for creating a DiscordPendingLink entity.
type DiscordPendingLinkCreate struct {
	config
	mutation *DiscordPendingLinkMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCode sets the "code" field.
func (_c *DiscordPendingLinkCreate) SetCode(v string) *DiscordPendingLinkCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetDiscordUserID sets the "discord_user_id" field.
func (_c *DiscordPendingLinkCreate) SetDiscordUserID(v string) *DiscordPendingLinkCreate {
	_c.mutation.SetDiscordUserID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *DiscordPendingLinkCreate) SetStatus(v string) *DiscordPendingLinkCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *DiscordPendingLinkCreate) SetNillableStatus(v *string) *DiscordPendingLinkCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *DiscordPendingLinkCreate) SetUserID(v string) *DiscordPendingLinkCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *DiscordPendingLinkCreate) SetNillableUserID(v *string) *DiscordPendingLinkCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetUserEmail sets the "user_email" field.
func (_c *DiscordPendingLinkCreate) SetUserEmail(v string) *DiscordPendingLinkCreate {
	_c.mutation.SetUserEmail(v)
	return _c
}

// SetNillableUserEmail sets the "user_email" field if the given value is not nil.
func (_c *DiscordPendingLinkCreate) SetNillableUserEmail(v *string) *DiscordPendingLinkCreate {
	if v != nil {
		_c.SetUserEmail(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *DiscordPendingLinkCreate) SetExpiresAt(v time.Time) *DiscordPendingLinkCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DiscordPendingLinkCreate) SetCreatedAt(v time.Time) *DiscordPendingLinkCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DiscordPendingLinkCreate) SetNillableCreatedAt(v *time.Time) *DiscordPendingLinkCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the DiscordPendingLinkMutation object of the builder.
func (_c *DiscordPendingLinkCreate) Mutation() *DiscordPendingLinkMutation {
	return _c.mutation
}

// Save creates the DiscordPendingLink in the database.
func (_c *DiscordPendingLinkCreate) Save(ctx context.Context) (*DiscordPendingLink, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DiscordPendingLinkCreate) SaveX(ctx context.Context) *DiscordPendingLink {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DiscordPendingLinkCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DiscordPendingLinkCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DiscordPendingLinkCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := discordpendinglink.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.UserID(); !ok {
		v := discordpendinglink.DefaultUserID
		_c.mutation.SetUserID(v)
	}
	if _, ok := _c.mutation.UserEmail(); !ok {
		v := discordpendinglink.DefaultUserEmail
		_c.mutation.SetUserEmail(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := discordpendinglink.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DiscordPendingLinkCreate) check() error {
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "DiscordPendingLink.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := discordpendinglink.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "DiscordPendingLink.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DiscordUserID(); !ok {
		return &ValidationError{Name: "discord_user_id", err: errors.New(`ent: missing required field "DiscordPendingLink.discord_user_id"`)}
	}
	if v, ok := _c.mutation.DiscordUserID(); ok {
		if err := discordpendinglink.DiscordUserIDValidator(v); err != nil {
			return &ValidationError{Name: "discord_user_id", err: fmt.Errorf(`ent: validator failed for field "DiscordPendingLink.discord_user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "DiscordPendingLink.status"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "DiscordPendingLink.user_id"`)}
	}
	if _, ok := _c.mutation.UserEmail(); !ok {
		return &ValidationError{Name: "user_email", err: errors.New(`ent: missing required field "DiscordPendingLink.user_email"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "DiscordPendingLink.expires_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DiscordPendingLink.created_at"`)}
	}
	return nil
}

func (_c *DiscordPendingLinkCreate) sqlSave(ctx context.Context) (*DiscordPendingLink, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DiscordPendingLinkCreate) createSpec() (*DiscordPendingLink, *sqlgraph.CreateSpec) {
	var (
		_node = &DiscordPendingLink{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(discordpendinglink.Table, sqlgraph.NewFieldSpec(discordpendinglink.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(discordpendinglink.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.DiscordUserID(); ok {
		_spec.SetField(discordpendinglink.FieldDiscordUserID, field.TypeString, value)
		_node.DiscordUserID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(discordpendinglink.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(discordpendinglink.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.UserEmail(); ok {
		_spec.SetField(discordpendinglink.FieldUserEmail, field.TypeString, value)
		_node.UserEmail = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(discordpendinglink.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(discordpendinglink.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DiscordPendingLink.Create().
//		SetCode(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DiscordPendingLinkUpsert) {
//			SetCode(v+v).
//		}).
//		Exec(ctx)
func (_c *DiscordPendingLinkCreate) OnConflict(opts ...sql.ConflictOption) *DiscordPendingLinkUpsertOne {
	_c.conflict = opts
	return &DiscordPendingLinkUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DiscordPendingLink.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DiscordPendingLinkCreate) OnConflictColumns(columns ...string) *DiscordPendingLinkUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DiscordPendingLinkUpsertOne{
		create: _c,
	}
}

type (
	// DiscordPendingLinkUpsertOne is the builder for "upsert"-ing
	//  one DiscordPendingLink node.
	DiscordPendingLinkUpsertOne struct {
		create *DiscordPendingLinkCreate
	}

	// DiscordPendingLinkUpsert is the "OnConflict" setter.
	DiscordPendingLinkUpsert struct {
		*sql.UpdateSet
	}
)

// SetCode sets the "code" field.
func (u *DiscordPendingLinkUpsert) SetCode(v string) *DiscordPendingLinkUpsert {
	u.Set(discordpendinglink.FieldCode, v)
	return u
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *DiscordPendingLinkUpsert) UpdateCode() *DiscordPendingLinkUpsert {
	u.SetExcluded(discordpendinglink.FieldCode)
	return u
}

// SetDiscordUserID sets the "discord_user_id" field.
func (u *DiscordPendingLinkUpsert) SetDiscordUserID(v string) *DiscordPendingLinkUpsert {
	u.Set(discordpendinglink.FieldDiscordUserID, v)
	return u
}

// UpdateDiscordUserID sets the "discord_user_id" field to the value that was provided on create.
func (u *DiscordPendingLinkUpsert) UpdateDiscordUserID() *DiscordPendingLinkUpsert {
	u.SetExcluded(discordpendinglink.FieldDiscordUserID)
	return u
}

// SetStatus sets the "status" field.
func (u *DiscordPendingLinkUpsert) SetStatus(v string) *DiscordPendingLinkUpsert {
	u.Set(discordpendinglink.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *DiscordPendingLinkUpsert) UpdateStatus() *DiscordPendingLinkUpsert {
	u.SetExcluded(discordpendinglink.FieldStatus)
	return u
}

// SetUserID sets the "user_id" field.
func (u *DiscordPendingLinkUpsert) SetUserID(v string) *DiscordPendingLinkUpsert {
	u.Set(discordpendinglink.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *DiscordPendingLinkUpsert) UpdateUserID() *DiscordPendingLinkUpsert {
	u.SetExcluded(discordpendinglink.FieldUserID)
	return u
}

// SetUserEmail sets the "user_email" field.
func (u *DiscordPendingLinkUpsert) SetUserEmail(v string) *DiscordPendingLinkUpsert {
	u.Set(discordpendinglink.FieldUserEmail, v)
	return u
}

// UpdateUserEmail sets the "user_email" field to the value that was provided on create.
func (u *DiscordPendingLinkUpsert) UpdateUserEmail() *DiscordPendingLinkUpsert {
	u.SetExcluded(discordpendinglink.FieldUserEmail)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *DiscordPendingLinkUpsert) SetExpiresAt(v time.Time) *DiscordPendingLinkUpsert {
	u.Set(discordpendinglink.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *DiscordPendingLinkUpsert) UpdateExpiresAt() *DiscordPendingLinkUpsert {
	u.SetExcluded(discordpendinglink.FieldExpiresAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.DiscordPendingLink.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *DiscordPendingLinkUpsertOne) UpdateNewValues() *DiscordPendingLinkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(discordpendinglink.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DiscordPendingLink.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DiscordPendingLinkUpsertOne) Ignore() *DiscordPendingLinkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DiscordPendingLinkUpsertOne) DoNothing() *DiscordPendingLinkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DiscordPendingLinkCreate.OnConflict
// documentation for more info.
func (u *DiscordPendingLinkUpsertOne) Update(set func(*DiscordPendingLinkUpsert)) *DiscordPendingLinkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DiscordPendingLinkUpsert{UpdateSet: update})
	}))
	return u
}

// SetCode sets the "code" field.
func (u *DiscordPendingLinkUpsertOne) SetCode(v string) *DiscordPendingLinkUpsertOne {
	return u.Update(func(s *DiscordPendingLinkUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *DiscordPendingLinkUpsertOne) UpdateCode() *DiscordPendingLinkUpsertOne {
	return u.Update(func(s *DiscordPendingLinkUpsert) {
		s.UpdateCode()
	})
}

// SetDiscordUserID sets the "discord_user_id" field.
func (u *DiscordPendingLinkUpsertOne) SetDiscordUserID(v string) *DiscordPendingLinkUpsertOne {
	return u.Update(func(s *DiscordPendingLinkUpsert) {
		s.SetDiscordUserID(v)
	})
}

// UpdateDiscordUserID sets the "discord_user_id" field to the value that was provided on create.
func (u *DiscordPendingLinkUpsertOne) UpdateDiscordUserID() *DiscordPendingLinkUpsertOne {
	return u.Update(func(s *DiscordPendingLinkUpsert) {
		s.UpdateDiscordUserID()
	})
}

// SetStatus sets the "status" field.
func (u *DiscordPendingLinkUpsertOne) SetStatus(v string) *DiscordPendingLinkUpsertOne {
	return u.Update(func(s *DiscordPendingLinkUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *DiscordPendingLinkUpsertOne) UpdateStatus() *DiscordPendingLinkUpsertOne {
	return u.Update(func(s *DiscordPendingLinkUpsert) {
		s.UpdateStatus()
	})
}

// SetUserID sets the "user_id" field.
func (u *DiscordPendingLinkUpsertOne) SetUserID(v string) *DiscordPendingLinkUpsertOne {
	return u.Update(func(s *DiscordPendingLinkUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *DiscordPendingLinkUpsertOne) UpdateUserID() *DiscordPendingLinkUpsertOne {
	return u.Update(func(s *DiscordPendingLinkUpsert) {
		s.UpdateUserID()
	})
}

// SetUserEmail sets the "user_email" field.
func (u *DiscordPendingLinkUpsertOne) SetUserEmail(v string) *DiscordPendingLinkUpsertOne {
	return u.Update(func(s *DiscordPendingLinkUpsert) {
		s.SetUserEmail(v)
	})
}

// UpdateUserEmail sets the "user_email" field to the value that was provided on create.
func (u *DiscordPendingLinkUpsertOne) UpdateUserEmail() *DiscordPendingLinkUpsertOne {
	return u.Update(func(s *DiscordPendingLinkUpsert) {
		s.UpdateUserEmail()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *DiscordPendingLinkUpsertOne) SetExpiresAt(v time.Time) *DiscordPendingLinkUpsertOne {
	return u.Update(func(s *DiscordPendingLinkUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *DiscordPendingLinkUpsertOne) UpdateExpiresAt() *DiscordPendingLinkUpsertOne {
	return u.Update(func(s *DiscordPendingLinkUpsert) {
		s.UpdateExpiresAt()
	})
}

// Exec executes the query.
func (u *DiscordPendingLinkUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DiscordPendingLinkCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DiscordPendingLinkUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DiscordPendingLinkUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DiscordPendingLinkUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DiscordPendingLinkCreateBulk is the builder for creating many DiscordPendingLink entities in bulk.
type DiscordPendingLinkCreateBulk struct {
	config
	err      error
	builders []*DiscordPendingLinkCreate
	conflict []sql.ConflictOption
}

// Save creates the DiscordPendingLink entities in the database.
func (_c *DiscordPendingLinkCreateBulk) Save(ctx context.Context) ([]*DiscordPendingLink, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DiscordPendingLink, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DiscordPendingLinkMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DiscordPendingLinkCreateBulk) SaveX(ctx context.Context) []*DiscordPendingLink {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DiscordPendingLinkCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DiscordPendingLinkCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DiscordPendingLink.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DiscordPendingLinkUpsert) {
//			SetCode(v+v).
//		}).
//		Exec(ctx)
func (_c *DiscordPendingLinkCreateBulk) OnConflict(opts ...sql.ConflictOption) *DiscordPendingLinkUpsertBulk {
	_c.conflict = opts
	return &DiscordPendingLinkUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DiscordPendingLink.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DiscordPendingLinkCreateBulk) OnConflictColumns(columns ...string) *DiscordPendingLinkUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DiscordPendingLinkUpsertBulk{
		create: _c,
	}
}

// DiscordPendingLinkUpsertBulk is the builder for "upsert"-ing
// a bulk of DiscordPendingLink nodes.
type DiscordPendingLinkUpsertBulk struct {
	create *DiscordPendingLinkCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.DiscordPendingLink.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *DiscordPendingLinkUpsertBulk) UpdateNewValues() *DiscordPendingLinkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(discordpendinglink.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DiscordPendingLink.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DiscordPendingLinkUpsertBulk) Ignore() *DiscordPendingLinkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DiscordPendingLinkUpsertBulk) DoNothing() *DiscordPendingLinkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DiscordPendingLinkCreateBulk.OnConflict
// documentation for more info.
func (u *DiscordPendingLinkUpsertBulk) Update(set func(*DiscordPendingLinkUpsert)) *DiscordPendingLinkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DiscordPendingLinkUpsert{UpdateSet: update})
	}))
	return u
}

// SetCode sets the "code" field.
func (u *DiscordPendingLinkUpsertBulk) SetCode(v string) *DiscordPendingLinkUpsertBulk {
	return u.Update(func(s *DiscordPendingLinkUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *DiscordPendingLinkUpsertBulk) UpdateCode() *DiscordPendingLinkUpsertBulk {
	return u.Update(func(s *DiscordPendingLinkUpsert) {
		s.UpdateCode()
	})
}

// SetDiscordUserID sets the "discord_user_id" field.
func (u *DiscordPendingLinkUpsertBulk) SetDiscordUserID(v string) *DiscordPendingLinkUpsertBulk {
	return u.Update(func(s *DiscordPendingLinkUpsert) {
		s.SetDiscordUserID(v)
	})
}

// UpdateDiscordUserID sets the "discord_user_id" field to the value that was provided on create.
func (u *DiscordPendingLinkUpsertBulk) UpdateDiscordUserID() *DiscordPendingLinkUpsertBulk {
	return u.Update(func(s *DiscordPendingLinkUpsert) {
		s.UpdateDiscordUserID()
	})
}

// SetStatus sets the "status" field.
func (u *DiscordPendingLinkUpsertBulk) SetStatus(v string) *DiscordPendingLinkUpsertBulk {
	return u.Update(func(s *DiscordPendingLinkUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *DiscordPendingLinkUpsertBulk) UpdateStatus() *DiscordPendingLinkUpsertBulk {
	return u.Update(func(s *DiscordPendingLinkUpsert) {
		s.UpdateStatus()
	})
}

// SetUserID sets the "user_id" field.
func (u *DiscordPendingLinkUpsertBulk) SetUserID(v string) *DiscordPendingLinkUpsertBulk {
	return u.Update(func(s *DiscordPendingLinkUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *DiscordPendingLinkUpsertBulk) UpdateUserID() *DiscordPendingLinkUpsertBulk {
	return u.Update(func(s *DiscordPendingLinkUpsert) {
		s.UpdateUserID()
	})
}

// SetUserEmail sets the "user_email" field.
func (u *DiscordPendingLinkUpsertBulk) SetUserEmail(v string) *DiscordPendingLinkUpsertBulk {
	return u.Update(func(s *DiscordPendingLinkUpsert) {
		s.SetUserEmail(v)
	})
}

// UpdateUserEmail sets the "user_email" field to the value that was provided on create.
func (u *DiscordPendingLinkUpsertBulk) UpdateUserEmail() *DiscordPendingLinkUpsertBulk {
	return u.Update(func(s *DiscordPendingLinkUpsert) {
		s.UpdateUserEmail()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *DiscordPendingLinkUpsertBulk) SetExpiresAt(v time.Time) *DiscordPendingLinkUpsertBulk {
	return u.Update(func(s *DiscordPendingLinkUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *DiscordPendingLinkUpsertBulk) UpdateExpiresAt() *DiscordPendingLinkUpsertBulk {
	return u.Update(func(s *DiscordPendingLinkUpsert) {
		s.UpdateExpiresAt()
	})
}

// Exec executes the query.
func (u *DiscordPendingLinkUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DiscordPendingLinkCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DiscordPendingLinkCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DiscordPendingLinkUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
