// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/pdlc-os/fabric/pkg/ent/discordpendinglink"
	"github.com/pdlc-os/fabric/pkg/ent/predicate"
)

// DiscordPendingLinkDelete is the builder for deleting a DiscordPendingLink entity.
type DiscordPendingLinkDelete struct {
	config
	hooks    []Hook
	mutation *DiscordPendingLinkMutation
}

// Where appends a list predicates to the DiscordPendingLinkDelete builder.
func (_d *DiscordPendingLinkDelete) Where(ps ...predicate.DiscordPendingLink) *DiscordPendingLinkDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *DiscordPendingLinkDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DiscordPendingLinkDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *DiscordPendingLinkDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(discordpendinglink.Table, sqlgraph.NewFieldSpec(discordpendinglink.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// DiscordPendingLinkDeleteOne is the builder for deleting a single DiscordPendingLink entity.
type DiscordPendingLinkDeleteOne struct {
	_d *DiscordPendingLinkDelete
}

// Where appends a list predicates to the DiscordPendingLinkDelete builder.
func (_d *DiscordPendingLinkDeleteOne) Where(ps ...predicate.DiscordPendingLink) *DiscordPendingLinkDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *DiscordPendingLinkDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{discordpendinglink.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DiscordPendingLinkDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
