// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/pdlc-os/fabric/pkg/ent/integrationconfig"
)

// IntegrationConfigCreate is the builder for creating a IntegrationConfig entity.
type IntegrationConfigCreate struct {
	config
	mutation *IntegrationConfigMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetIntegration sets the "integration" field.
func (_c *IntegrationConfigCreate) SetIntegration(v string) *IntegrationConfigCreate {
	_c.mutation.SetIntegration(v)
	return _c
}

// SetConfig sets the "config" field.
func (_c *IntegrationConfigCreate) SetConfig(v string) *IntegrationConfigCreate {
	_c.mutation.SetConfig(v)
	return _c
}

// SetNillableConfig sets the "config" field if the given value is not nil.
func (_c *IntegrationConfigCreate) SetNillableConfig(v *string) *IntegrationConfigCreate {
	if v != nil {
		_c.SetConfig(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *IntegrationConfigCreate) SetEnabled(v bool) *IntegrationConfigCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *IntegrationConfigCreate) SetNillableEnabled(v *bool) *IntegrationConfigCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *IntegrationConfigCreate) SetUpdatedBy(v string) *IntegrationConfigCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *IntegrationConfigCreate) SetNillableUpdatedBy(v *string) *IntegrationConfigCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetCreateTime sets the "create_time" field.
func (_c *IntegrationConfigCreate) SetCreateTime(v time.Time) *IntegrationConfigCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *IntegrationConfigCreate) SetNillableCreateTime(v *time.Time) *IntegrationConfigCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *IntegrationConfigCreate) SetUpdateTime(v time.Time) *IntegrationConfigCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *IntegrationConfigCreate) SetNillableUpdateTime(v *time.Time) *IntegrationConfigCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *IntegrationConfigCreate) SetID(v uuid.UUID) *IntegrationConfigCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *IntegrationConfigCreate) SetNillableID(v *uuid.UUID) *IntegrationConfigCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the IntegrationConfigMutation object of the builder.
func (_c *IntegrationConfigCreate) Mutation() *IntegrationConfigMutation {
	return _c.mutation
}

// Save creates the IntegrationConfig in the database.
func (_c *IntegrationConfigCreate) Save(ctx context.Context) (*IntegrationConfig, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *IntegrationConfigCreate) SaveX(ctx context.Context) *IntegrationConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IntegrationConfigCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IntegrationConfigCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *IntegrationConfigCreate) defaults() {
	if _, ok := _c.mutation.Config(); !ok {
		v := integrationconfig.DefaultConfig
		_c.mutation.SetConfig(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := integrationconfig.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := integrationconfig.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := integrationconfig.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := integrationconfig.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *IntegrationConfigCreate) check() error {
	if _, ok := _c.mutation.Integration(); !ok {
		return &ValidationError{Name: "integration", err: errors.New(`ent: missing required field "IntegrationConfig.integration"`)}
	}
	if v, ok := _c.mutation.Integration(); ok {
		if err := integrationconfig.IntegrationValidator(v); err != nil {
			return &ValidationError{Name: "integration", err: fmt.Errorf(`ent: validator failed for field "IntegrationConfig.integration": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Config(); !ok {
		return &ValidationError{Name: "config", err: errors.New(`ent: missing required field "IntegrationConfig.config"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "IntegrationConfig.enabled"`)}
	}
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "IntegrationConfig.create_time"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "IntegrationConfig.update_time"`)}
	}
	return nil
}

func (_c *IntegrationConfigCreate) sqlSave(ctx context.Context) (*IntegrationConfig, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *IntegrationConfigCreate) createSpec() (*IntegrationConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &IntegrationConfig{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(integrationconfig.Table, sqlgraph.NewFieldSpec(integrationconfig.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Integration(); ok {
		_spec.SetField(integrationconfig.FieldIntegration, field.TypeString, value)
		_node.Integration = value
	}
	if value, ok := _c.mutation.Config(); ok {
		_spec.SetField(integrationconfig.FieldConfig, field.TypeString, value)
		_node.Config = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(integrationconfig.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(integrationconfig.FieldUpdatedBy, field.TypeString, value)
		_node.UpdatedBy = value
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(integrationconfig.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(integrationconfig.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.IntegrationConfig.Create().
//		SetIntegration(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.IntegrationConfigUpsert) {
//			SetIntegration(v+v).
//		}).
//		Exec(ctx)
func (_c *IntegrationConfigCreate) OnConflict(opts ...sql.ConflictOption) *IntegrationConfigUpsertOne {
	_c.conflict = opts
	return &IntegrationConfigUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.IntegrationConfig.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *IntegrationConfigCreate) OnConflictColumns(columns ...string) *IntegrationConfigUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &IntegrationConfigUpsertOne{
		create: _c,
	}
}

type (
	// IntegrationConfigUpsertOne is the builder for "upsert"-ing
	//  one IntegrationConfig node.
	IntegrationConfigUpsertOne struct {
		create *IntegrationConfigCreate
	}

	// IntegrationConfigUpsert is the "OnConflict" setter.
	IntegrationConfigUpsert struct {
		*sql.UpdateSet
	}
)

// SetIntegration sets the "integration" field.
func (u *IntegrationConfigUpsert) SetIntegration(v string) *IntegrationConfigUpsert {
	u.Set(integrationconfig.FieldIntegration, v)
	return u
}

// UpdateIntegration sets the "integration" field to the value that was provided on create.
func (u *IntegrationConfigUpsert) UpdateIntegration() *IntegrationConfigUpsert {
	u.SetExcluded(integrationconfig.FieldIntegration)
	return u
}

// SetConfig sets the "config" field.
func (u *IntegrationConfigUpsert) SetConfig(v string) *IntegrationConfigUpsert {
	u.Set(integrationconfig.FieldConfig, v)
	return u
}

// UpdateConfig sets the "config" field to the value that was provided on create.
func (u *IntegrationConfigUpsert) UpdateConfig() *IntegrationConfigUpsert {
	u.SetExcluded(integrationconfig.FieldConfig)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *IntegrationConfigUpsert) SetEnabled(v bool) *IntegrationConfigUpsert {
	u.Set(integrationconfig.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *IntegrationConfigUpsert) UpdateEnabled() *IntegrationConfigUpsert {
	u.SetExcluded(integrationconfig.FieldEnabled)
	return u
}

// SetUpdatedBy sets the "updated_by" field.
func (u *IntegrationConfigUpsert) SetUpdatedBy(v string) *IntegrationConfigUpsert {
	u.Set(integrationconfig.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *IntegrationConfigUpsert) UpdateUpdatedBy() *IntegrationConfigUpsert {
	u.SetExcluded(integrationconfig.FieldUpdatedBy)
	return u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *IntegrationConfigUpsert) ClearUpdatedBy() *IntegrationConfigUpsert {
	u.SetNull(integrationconfig.FieldUpdatedBy)
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *IntegrationConfigUpsert) SetUpdateTime(v time.Time) *IntegrationConfigUpsert {
	u.Set(integrationconfig.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *IntegrationConfigUpsert) UpdateUpdateTime() *IntegrationConfigUpsert {
	u.SetExcluded(integrationconfig.FieldUpdateTime)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.IntegrationConfig.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(integrationconfig.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *IntegrationConfigUpsertOne) UpdateNewValues() *IntegrationConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(integrationconfig.FieldID)
		}
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(integrationconfig.FieldCreateTime)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.IntegrationConfig.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *IntegrationConfigUpsertOne) Ignore() *IntegrationConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *IntegrationConfigUpsertOne) DoNothing() *IntegrationConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the IntegrationConfigCreate.OnConflict
// documentation for more info.
func (u *IntegrationConfigUpsertOne) Update(set func(*IntegrationConfigUpsert)) *IntegrationConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&IntegrationConfigUpsert{UpdateSet: update})
	}))
	return u
}

// SetIntegration sets the "integration" field.
func (u *IntegrationConfigUpsertOne) SetIntegration(v string) *IntegrationConfigUpsertOne {
	return u.Update(func(s *IntegrationConfigUpsert) {
		s.SetIntegration(v)
	})
}

// UpdateIntegration sets the "integration" field to the value that was provided on create.
func (u *IntegrationConfigUpsertOne) UpdateIntegration() *IntegrationConfigUpsertOne {
	return u.Update(func(s *IntegrationConfigUpsert) {
		s.UpdateIntegration()
	})
}

// SetConfig sets the "config" field.
func (u *IntegrationConfigUpsertOne) SetConfig(v string) *IntegrationConfigUpsertOne {
	return u.Update(func(s *IntegrationConfigUpsert) {
		s.SetConfig(v)
	})
}

// UpdateConfig sets the "config" field to the value that was provided on create.
func (u *IntegrationConfigUpsertOne) UpdateConfig() *IntegrationConfigUpsertOne {
	return u.Update(func(s *IntegrationConfigUpsert) {
		s.UpdateConfig()
	})
}

// SetEnabled sets the "enabled" field.
func (u *IntegrationConfigUpsertOne) SetEnabled(v bool) *IntegrationConfigUpsertOne {
	return u.Update(func(s *IntegrationConfigUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *IntegrationConfigUpsertOne) UpdateEnabled() *IntegrationConfigUpsertOne {
	return u.Update(func(s *IntegrationConfigUpsert) {
		s.UpdateEnabled()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *IntegrationConfigUpsertOne) SetUpdatedBy(v string) *IntegrationConfigUpsertOne {
	return u.Update(func(s *IntegrationConfigUpsert) {
		s.SetUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *IntegrationConfigUpsertOne) UpdateUpdatedBy() *IntegrationConfigUpsertOne {
	return u.Update(func(s *IntegrationConfigUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *IntegrationConfigUpsertOne) ClearUpdatedBy() *IntegrationConfigUpsertOne {
	return u.Update(func(s *IntegrationConfigUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetUpdateTime sets the "update_time" field.
func (u *IntegrationConfigUpsertOne) SetUpdateTime(v time.Time) *IntegrationConfigUpsertOne {
	return u.Update(func(s *IntegrationConfigUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *IntegrationConfigUpsertOne) UpdateUpdateTime() *IntegrationConfigUpsertOne {
	return u.Update(func(s *IntegrationConfigUpsert) {
		s.UpdateUpdateTime()
	})
}

// Exec executes the query.
func (u *IntegrationConfigUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for IntegrationConfigCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *IntegrationConfigUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *IntegrationConfigUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: IntegrationConfigUpsertOne.ID is not supported by MySQL driver. Use IntegrationConfigUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *IntegrationConfigUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// IntegrationConfigCreateBulk is the builder for creating many IntegrationConfig entities in bulk.
type IntegrationConfigCreateBulk struct {
	config
	err      error
	builders []*IntegrationConfigCreate
	conflict []sql.ConflictOption
}

// Save creates the IntegrationConfig entities in the database.
func (_c *IntegrationConfigCreateBulk) Save(ctx context.Context) ([]*IntegrationConfig, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*IntegrationConfig, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*IntegrationConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *IntegrationConfigCreateBulk) SaveX(ctx context.Context) []*IntegrationConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IntegrationConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IntegrationConfigCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.IntegrationConfig.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.IntegrationConfigUpsert) {
//			SetIntegration(v+v).
//		}).
//		Exec(ctx)
func (_c *IntegrationConfigCreateBulk) OnConflict(opts ...sql.ConflictOption) *IntegrationConfigUpsertBulk {
	_c.conflict = opts
	return &IntegrationConfigUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.IntegrationConfig.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *IntegrationConfigCreateBulk) OnConflictColumns(columns ...string) *IntegrationConfigUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &IntegrationConfigUpsertBulk{
		create: _c,
	}
}

// IntegrationConfigUpsertBulk is the builder for "upsert"-ing
// a bulk of IntegrationConfig nodes.
type IntegrationConfigUpsertBulk struct {
	create *IntegrationConfigCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.IntegrationConfig.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(integrationconfig.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *IntegrationConfigUpsertBulk) UpdateNewValues() *IntegrationConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(integrationconfig.FieldID)
			}
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(integrationconfig.FieldCreateTime)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.IntegrationConfig.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *IntegrationConfigUpsertBulk) Ignore() *IntegrationConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *IntegrationConfigUpsertBulk) DoNothing() *IntegrationConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the IntegrationConfigCreateBulk.OnConflict
// documentation for more info.
func (u *IntegrationConfigUpsertBulk) Update(set func(*IntegrationConfigUpsert)) *IntegrationConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&IntegrationConfigUpsert{UpdateSet: update})
	}))
	return u
}

// SetIntegration sets the "integration" field.
func (u *IntegrationConfigUpsertBulk) SetIntegration(v string) *IntegrationConfigUpsertBulk {
	return u.Update(func(s *IntegrationConfigUpsert) {
		s.SetIntegration(v)
	})
}

// UpdateIntegration sets the "integration" field to the value that was provided on create.
func (u *IntegrationConfigUpsertBulk) UpdateIntegration() *IntegrationConfigUpsertBulk {
	return u.Update(func(s *IntegrationConfigUpsert) {
		s.UpdateIntegration()
	})
}

// SetConfig sets the "config" field.
func (u *IntegrationConfigUpsertBulk) SetConfig(v string) *IntegrationConfigUpsertBulk {
	return u.Update(func(s *IntegrationConfigUpsert) {
		s.SetConfig(v)
	})
}

// UpdateConfig sets the "config" field to the value that was provided on create.
func (u *IntegrationConfigUpsertBulk) UpdateConfig() *IntegrationConfigUpsertBulk {
	return u.Update(func(s *IntegrationConfigUpsert) {
		s.UpdateConfig()
	})
}

// SetEnabled sets the "enabled" field.
func (u *IntegrationConfigUpsertBulk) SetEnabled(v bool) *IntegrationConfigUpsertBulk {
	return u.Update(func(s *IntegrationConfigUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *IntegrationConfigUpsertBulk) UpdateEnabled() *IntegrationConfigUpsertBulk {
	return u.Update(func(s *IntegrationConfigUpsert) {
		s.UpdateEnabled()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *IntegrationConfigUpsertBulk) SetUpdatedBy(v string) *IntegrationConfigUpsertBulk {
	return u.Update(func(s *IntegrationConfigUpsert) {
		s.SetUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *IntegrationConfigUpsertBulk) UpdateUpdatedBy() *IntegrationConfigUpsertBulk {
	return u.Update(func(s *IntegrationConfigUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *IntegrationConfigUpsertBulk) ClearUpdatedBy() *IntegrationConfigUpsertBulk {
	return u.Update(func(s *IntegrationConfigUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetUpdateTime sets the "update_time" field.
func (u *IntegrationConfigUpsertBulk) SetUpdateTime(v time.Time) *IntegrationConfigUpsertBulk {
	return u.Update(func(s *IntegrationConfigUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *IntegrationConfigUpsertBulk) UpdateUpdateTime() *IntegrationConfigUpsertBulk {
	return u.Update(func(s *IntegrationConfigUpsert) {
		s.UpdateUpdateTime()
	})
}

// Exec executes the query.
func (u *IntegrationConfigUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the IntegrationConfigCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for IntegrationConfigCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *IntegrationConfigUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
