// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/pdlc-os/fabric/pkg/ent/integrationconfig"
)

// IntegrationConfig is the model entity for the IntegrationConfig schema.
type IntegrationConfig struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Integration holds the value of the "integration" field.
	Integration string `json:"integration,omitempty"`
	// Config holds the value of the "config" field.
	Config string `json:"config,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// UpdatedBy holds the value of the "updated_by" field.
	UpdatedBy string `json:"updated_by,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime   time.Time `json:"update_time,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*IntegrationConfig) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case integrationconfig.FieldEnabled:
			values[i] = new(sql.NullBool)
		case integrationconfig.FieldIntegration, integrationconfig.FieldConfig, integrationconfig.FieldUpdatedBy:
			values[i] = new(sql.NullString)
		case integrationconfig.FieldCreateTime, integrationconfig.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		case integrationconfig.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the IntegrationConfig fields.
func (_m *IntegrationConfig) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case integrationconfig.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case integrationconfig.FieldIntegration:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field integration", values[i])
			} else if value.Valid {
				_m.Integration = value.String
			}
		case integrationconfig.FieldConfig:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field config", values[i])
			} else if value.Valid {
				_m.Config = value.String
			}
		case integrationconfig.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case integrationconfig.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = value.String
			}
		case integrationconfig.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = value.Time
			}
		case integrationconfig.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the IntegrationConfig.
// This includes values selected through modifiers, order, etc.
func (_m *IntegrationConfig) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this IntegrationConfig.
// Note that you need to call IntegrationConfig.Unwrap() before calling this method if this IntegrationConfig
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *IntegrationConfig) Update() *IntegrationConfigUpdateOne {
	return NewIntegrationConfigClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the IntegrationConfig entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *IntegrationConfig) Unwrap() *IntegrationConfig {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: IntegrationConfig is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *IntegrationConfig) String() string {
	var builder strings.Builder
	builder.WriteString("IntegrationConfig(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("integration=")
	builder.WriteString(_m.Integration)
	builder.WriteString(", ")
	builder.WriteString("config=")
	builder.WriteString(_m.Config)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("updated_by=")
	builder.WriteString(_m.UpdatedBy)
	builder.WriteString(", ")
	builder.WriteString("create_time=")
	builder.WriteString(_m.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(_m.UpdateTime.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// IntegrationConfigs is a parsable slice of IntegrationConfig.
type IntegrationConfigs []*IntegrationConfig
