// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/pdlc-os/fabric/pkg/ent/integrationupdate"
)

// IntegrationUpdate is the model entity for the IntegrationUpdate schema.
type IntegrationUpdate struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Integration holds the value of the "integration" field.
	Integration string `json:"integration,omitempty"`
	// State holds the value of the "state" field.
	State integrationupdate.State `json:"state,omitempty"`
	// Detail holds the value of the "detail" field.
	Detail string `json:"detail,omitempty"`
	// NewVersion holds the value of the "new_version" field.
	NewVersion string `json:"new_version,omitempty"`
	// RequestedBy holds the value of the "requested_by" field.
	RequestedBy string `json:"requested_by,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime   time.Time `json:"update_time,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*IntegrationUpdate) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case integrationupdate.FieldIntegration, integrationupdate.FieldState, integrationupdate.FieldDetail, integrationupdate.FieldNewVersion, integrationupdate.FieldRequestedBy:
			values[i] = new(sql.NullString)
		case integrationupdate.FieldCreateTime, integrationupdate.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		case integrationupdate.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the IntegrationUpdate fields.
func (_m *IntegrationUpdate) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case integrationupdate.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case integrationupdate.FieldIntegration:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field integration", values[i])
			} else if value.Valid {
				_m.Integration = value.String
			}
		case integrationupdate.FieldState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field state", values[i])
			} else if value.Valid {
				_m.State = integrationupdate.State(value.String)
			}
		case integrationupdate.FieldDetail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field detail", values[i])
			} else if value.Valid {
				_m.Detail = value.String
			}
		case integrationupdate.FieldNewVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field new_version", values[i])
			} else if value.Valid {
				_m.NewVersion = value.String
			}
		case integrationupdate.FieldRequestedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field requested_by", values[i])
			} else if value.Valid {
				_m.RequestedBy = value.String
			}
		case integrationupdate.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = value.Time
			}
		case integrationupdate.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the IntegrationUpdate.
// This includes values selected through modifiers, order, etc.
func (_m *IntegrationUpdate) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this IntegrationUpdate.
// Note that you need to call IntegrationUpdate.Unwrap() before calling this method if this IntegrationUpdate
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *IntegrationUpdate) Update() *IntegrationUpdateUpdateOne {
	return NewIntegrationUpdateClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the IntegrationUpdate entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *IntegrationUpdate) Unwrap() *IntegrationUpdate {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: IntegrationUpdate is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *IntegrationUpdate) String() string {
	var builder strings.Builder
	builder.WriteString("IntegrationUpdate(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("integration=")
	builder.WriteString(_m.Integration)
	builder.WriteString(", ")
	builder.WriteString("state=")
	builder.WriteString(fmt.Sprintf("%v", _m.State))
	builder.WriteString(", ")
	builder.WriteString("detail=")
	builder.WriteString(_m.Detail)
	builder.WriteString(", ")
	builder.WriteString("new_version=")
	builder.WriteString(_m.NewVersion)
	builder.WriteString(", ")
	builder.WriteString("requested_by=")
	builder.WriteString(_m.RequestedBy)
	builder.WriteString(", ")
	builder.WriteString("create_time=")
	builder.WriteString(_m.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(_m.UpdateTime.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// IntegrationUpdates is a parsable slice of IntegrationUpdate.
type IntegrationUpdates []*IntegrationUpdate
