// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/pdlc-os/fabric/pkg/ent/integrationupdate"
)

// IntegrationUpdateCreate is the builder for creating a IntegrationUpdate entity.
type IntegrationUpdateCreate struct {
	config
	mutation *IntegrationUpdateMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetIntegration sets the "integration" field.
func (_c *IntegrationUpdateCreate) SetIntegration(v string) *IntegrationUpdateCreate {
	_c.mutation.SetIntegration(v)
	return _c
}

// SetState sets the "state" field.
func (_c *IntegrationUpdateCreate) SetState(v integrationupdate.State) *IntegrationUpdateCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_c *IntegrationUpdateCreate) SetNillableState(v *integrationupdate.State) *IntegrationUpdateCreate {
	if v != nil {
		_c.SetState(*v)
	}
	return _c
}

// SetDetail sets the "detail" field.
func (_c *IntegrationUpdateCreate) SetDetail(v string) *IntegrationUpdateCreate {
	_c.mutation.SetDetail(v)
	return _c
}

// SetNillableDetail sets the "detail" field if the given value is not nil.
func (_c *IntegrationUpdateCreate) SetNillableDetail(v *string) *IntegrationUpdateCreate {
	if v != nil {
		_c.SetDetail(*v)
	}
	return _c
}

// SetNewVersion sets the "new_version" field.
func (_c *IntegrationUpdateCreate) SetNewVersion(v string) *IntegrationUpdateCreate {
	_c.mutation.SetNewVersion(v)
	return _c
}

// SetNillableNewVersion sets the "new_version" field if the given value is not nil.
func (_c *IntegrationUpdateCreate) SetNillableNewVersion(v *string) *IntegrationUpdateCreate {
	if v != nil {
		_c.SetNewVersion(*v)
	}
	return _c
}

// SetRequestedBy sets the "requested_by" field.
func (_c *IntegrationUpdateCreate) SetRequestedBy(v string) *IntegrationUpdateCreate {
	_c.mutation.SetRequestedBy(v)
	return _c
}

// SetNillableRequestedBy sets the "requested_by" field if the given value is not nil.
func (_c *IntegrationUpdateCreate) SetNillableRequestedBy(v *string) *IntegrationUpdateCreate {
	if v != nil {
		_c.SetRequestedBy(*v)
	}
	return _c
}

// SetCreateTime sets the "create_time" field.
func (_c *IntegrationUpdateCreate) SetCreateTime(v time.Time) *IntegrationUpdateCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *IntegrationUpdateCreate) SetNillableCreateTime(v *time.Time) *IntegrationUpdateCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *IntegrationUpdateCreate) SetUpdateTime(v time.Time) *IntegrationUpdateCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *IntegrationUpdateCreate) SetNillableUpdateTime(v *time.Time) *IntegrationUpdateCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *IntegrationUpdateCreate) SetID(v uuid.UUID) *IntegrationUpdateCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *IntegrationUpdateCreate) SetNillableID(v *uuid.UUID) *IntegrationUpdateCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the IntegrationUpdateMutation object of the builder.
func (_c *IntegrationUpdateCreate) Mutation() *IntegrationUpdateMutation {
	return _c.mutation
}

// Save creates the IntegrationUpdate in the database.
func (_c *IntegrationUpdateCreate) Save(ctx context.Context) (*IntegrationUpdate, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *IntegrationUpdateCreate) SaveX(ctx context.Context) *IntegrationUpdate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IntegrationUpdateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IntegrationUpdateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *IntegrationUpdateCreate) defaults() {
	if _, ok := _c.mutation.State(); !ok {
		v := integrationupdate.DefaultState
		_c.mutation.SetState(v)
	}
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := integrationupdate.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := integrationupdate.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := integrationupdate.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *IntegrationUpdateCreate) check() error {
	if _, ok := _c.mutation.Integration(); !ok {
		return &ValidationError{Name: "integration", err: errors.New(`ent: missing required field "IntegrationUpdate.integration"`)}
	}
	if v, ok := _c.mutation.Integration(); ok {
		if err := integrationupdate.IntegrationValidator(v); err != nil {
			return &ValidationError{Name: "integration", err: fmt.Errorf(`ent: validator failed for field "IntegrationUpdate.integration": %w`, err)}
		}
	}
	if _, ok := _c.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`ent: missing required field "IntegrationUpdate.state"`)}
	}
	if v, ok := _c.mutation.State(); ok {
		if err := integrationupdate.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "IntegrationUpdate.state": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "IntegrationUpdate.create_time"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "IntegrationUpdate.update_time"`)}
	}
	return nil
}

func (_c *IntegrationUpdateCreate) sqlSave(ctx context.Context) (*IntegrationUpdate, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *IntegrationUpdateCreate) createSpec() (*IntegrationUpdate, *sqlgraph.CreateSpec) {
	var (
		_node = &IntegrationUpdate{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(integrationupdate.Table, sqlgraph.NewFieldSpec(integrationupdate.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Integration(); ok {
		_spec.SetField(integrationupdate.FieldIntegration, field.TypeString, value)
		_node.Integration = value
	}
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(integrationupdate.FieldState, field.TypeEnum, value)
		_node.State = value
	}
	if value, ok := _c.mutation.Detail(); ok {
		_spec.SetField(integrationupdate.FieldDetail, field.TypeString, value)
		_node.Detail = value
	}
	if value, ok := _c.mutation.NewVersion(); ok {
		_spec.SetField(integrationupdate.FieldNewVersion, field.TypeString, value)
		_node.NewVersion = value
	}
	if value, ok := _c.mutation.RequestedBy(); ok {
		_spec.SetField(integrationupdate.FieldRequestedBy, field.TypeString, value)
		_node.RequestedBy = value
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(integrationupdate.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(integrationupdate.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.IntegrationUpdate.Create().
//		SetIntegration(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.IntegrationUpdateUpsert) {
//			SetIntegration(v+v).
//		}).
//		Exec(ctx)
func (_c *IntegrationUpdateCreate) OnConflict(opts ...sql.ConflictOption) *IntegrationUpdateUpsertOne {
	_c.conflict = opts
	return &IntegrationUpdateUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.IntegrationUpdate.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *IntegrationUpdateCreate) OnConflictColumns(columns ...string) *IntegrationUpdateUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &IntegrationUpdateUpsertOne{
		create: _c,
	}
}

type (
	// IntegrationUpdateUpsertOne is the builder for "upsert"-ing
	//  one IntegrationUpdate node.
	IntegrationUpdateUpsertOne struct {
		create *IntegrationUpdateCreate
	}

	// IntegrationUpdateUpsert is the "OnConflict" setter.
	IntegrationUpdateUpsert struct {
		*sql.UpdateSet
	}
)

// SetIntegration sets the "integration" field.
func (u *IntegrationUpdateUpsert) SetIntegration(v string) *IntegrationUpdateUpsert {
	u.Set(integrationupdate.FieldIntegration, v)
	return u
}

// UpdateIntegration sets the "integration" field to the value that was provided on create.
func (u *IntegrationUpdateUpsert) UpdateIntegration() *IntegrationUpdateUpsert {
	u.SetExcluded(integrationupdate.FieldIntegration)
	return u
}

// SetState sets the "state" field.
func (u *IntegrationUpdateUpsert) SetState(v integrationupdate.State) *IntegrationUpdateUpsert {
	u.Set(integrationupdate.FieldState, v)
	return u
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *IntegrationUpdateUpsert) UpdateState() *IntegrationUpdateUpsert {
	u.SetExcluded(integrationupdate.FieldState)
	return u
}

// SetDetail sets the "detail" field.
func (u *IntegrationUpdateUpsert) SetDetail(v string) *IntegrationUpdateUpsert {
	u.Set(integrationupdate.FieldDetail, v)
	return u
}

// UpdateDetail sets the "detail" field to the value that was provided on create.
func (u *IntegrationUpdateUpsert) UpdateDetail() *IntegrationUpdateUpsert {
	u.SetExcluded(integrationupdate.FieldDetail)
	return u
}

// ClearDetail clears the value of the "detail" field.
func (u *IntegrationUpdateUpsert) ClearDetail() *IntegrationUpdateUpsert {
	u.SetNull(integrationupdate.FieldDetail)
	return u
}

// SetNewVersion sets the "new_version" field.
func (u *IntegrationUpdateUpsert) SetNewVersion(v string) *IntegrationUpdateUpsert {
	u.Set(integrationupdate.FieldNewVersion, v)
	return u
}

// UpdateNewVersion sets the "new_version" field to the value that was provided on create.
func (u *IntegrationUpdateUpsert) UpdateNewVersion() *IntegrationUpdateUpsert {
	u.SetExcluded(integrationupdate.FieldNewVersion)
	return u
}

// ClearNewVersion clears the value of the "new_version" field.
func (u *IntegrationUpdateUpsert) ClearNewVersion() *IntegrationUpdateUpsert {
	u.SetNull(integrationupdate.FieldNewVersion)
	return u
}

// SetRequestedBy sets the "requested_by" field.
func (u *IntegrationUpdateUpsert) SetRequestedBy(v string) *IntegrationUpdateUpsert {
	u.Set(integrationupdate.FieldRequestedBy, v)
	return u
}

// UpdateRequestedBy sets the "requested_by" field to the value that was provided on create.
func (u *IntegrationUpdateUpsert) UpdateRequestedBy() *IntegrationUpdateUpsert {
	u.SetExcluded(integrationupdate.FieldRequestedBy)
	return u
}

// ClearRequestedBy clears the value of the "requested_by" field.
func (u *IntegrationUpdateUpsert) ClearRequestedBy() *IntegrationUpdateUpsert {
	u.SetNull(integrationupdate.FieldRequestedBy)
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *IntegrationUpdateUpsert) SetUpdateTime(v time.Time) *IntegrationUpdateUpsert {
	u.Set(integrationupdate.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *IntegrationUpdateUpsert) UpdateUpdateTime() *IntegrationUpdateUpsert {
	u.SetExcluded(integrationupdate.FieldUpdateTime)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.IntegrationUpdate.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(integrationupdate.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *IntegrationUpdateUpsertOne) UpdateNewValues() *IntegrationUpdateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(integrationupdate.FieldID)
		}
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(integrationupdate.FieldCreateTime)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.IntegrationUpdate.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *IntegrationUpdateUpsertOne) Ignore() *IntegrationUpdateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *IntegrationUpdateUpsertOne) DoNothing() *IntegrationUpdateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the IntegrationUpdateCreate.OnConflict
// documentation for more info.
func (u *IntegrationUpdateUpsertOne) Update(set func(*IntegrationUpdateUpsert)) *IntegrationUpdateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&IntegrationUpdateUpsert{UpdateSet: update})
	}))
	return u
}

// SetIntegration sets the "integration" field.
func (u *IntegrationUpdateUpsertOne) SetIntegration(v string) *IntegrationUpdateUpsertOne {
	return u.Update(func(s *IntegrationUpdateUpsert) {
		s.SetIntegration(v)
	})
}

// UpdateIntegration sets the "integration" field to the value that was provided on create.
func (u *IntegrationUpdateUpsertOne) UpdateIntegration() *IntegrationUpdateUpsertOne {
	return u.Update(func(s *IntegrationUpdateUpsert) {
		s.UpdateIntegration()
	})
}

// SetState sets the "state" field.
func (u *IntegrationUpdateUpsertOne) SetState(v integrationupdate.State) *IntegrationUpdateUpsertOne {
	return u.Update(func(s *IntegrationUpdateUpsert) {
		s.SetState(v)
	})
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *IntegrationUpdateUpsertOne) UpdateState() *IntegrationUpdateUpsertOne {
	return u.Update(func(s *IntegrationUpdateUpsert) {
		s.UpdateState()
	})
}

// SetDetail sets the "detail" field.
func (u *IntegrationUpdateUpsertOne) SetDetail(v string) *IntegrationUpdateUpsertOne {
	return u.Update(func(s *IntegrationUpdateUpsert) {
		s.SetDetail(v)
	})
}

// UpdateDetail sets the "detail" field to the value that was provided on create.
func (u *IntegrationUpdateUpsertOne) UpdateDetail() *IntegrationUpdateUpsertOne {
	return u.Update(func(s *IntegrationUpdateUpsert) {
		s.UpdateDetail()
	})
}

// ClearDetail clears the value of the "detail" field.
func (u *IntegrationUpdateUpsertOne) ClearDetail() *IntegrationUpdateUpsertOne {
	return u.Update(func(s *IntegrationUpdateUpsert) {
		s.ClearDetail()
	})
}

// SetNewVersion sets the "new_version" field.
func (u *IntegrationUpdateUpsertOne) SetNewVersion(v string) *IntegrationUpdateUpsertOne {
	return u.Update(func(s *IntegrationUpdateUpsert) {
		s.SetNewVersion(v)
	})
}

// UpdateNewVersion sets the "new_version" field to the value that was provided on create.
func (u *IntegrationUpdateUpsertOne) UpdateNewVersion() *IntegrationUpdateUpsertOne {
	return u.Update(func(s *IntegrationUpdateUpsert) {
		s.UpdateNewVersion()
	})
}

// ClearNewVersion clears the value of the "new_version" field.
func (u *IntegrationUpdateUpsertOne) ClearNewVersion() *IntegrationUpdateUpsertOne {
	return u.Update(func(s *IntegrationUpdateUpsert) {
		s.ClearNewVersion()
	})
}

// SetRequestedBy sets the "requested_by" field.
func (u *IntegrationUpdateUpsertOne) SetRequestedBy(v string) *IntegrationUpdateUpsertOne {
	return u.Update(func(s *IntegrationUpdateUpsert) {
		s.SetRequestedBy(v)
	})
}

// UpdateRequestedBy sets the "requested_by" field to the value that was provided on create.
func (u *IntegrationUpdateUpsertOne) UpdateRequestedBy() *IntegrationUpdateUpsertOne {
	return u.Update(func(s *IntegrationUpdateUpsert) {
		s.UpdateRequestedBy()
	})
}

// ClearRequestedBy clears the value of the "requested_by" field.
func (u *IntegrationUpdateUpsertOne) ClearRequestedBy() *IntegrationUpdateUpsertOne {
	return u.Update(func(s *IntegrationUpdateUpsert) {
		s.ClearRequestedBy()
	})
}

// SetUpdateTime sets the "update_time" field.
func (u *IntegrationUpdateUpsertOne) SetUpdateTime(v time.Time) *IntegrationUpdateUpsertOne {
	return u.Update(func(s *IntegrationUpdateUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *IntegrationUpdateUpsertOne) UpdateUpdateTime() *IntegrationUpdateUpsertOne {
	return u.Update(func(s *IntegrationUpdateUpsert) {
		s.UpdateUpdateTime()
	})
}

// Exec executes the query.
func (u *IntegrationUpdateUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for IntegrationUpdateCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *IntegrationUpdateUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *IntegrationUpdateUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: IntegrationUpdateUpsertOne.ID is not supported by MySQL driver. Use IntegrationUpdateUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *IntegrationUpdateUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// IntegrationUpdateCreateBulk is the builder for creating many IntegrationUpdate entities in bulk.
type IntegrationUpdateCreateBulk struct {
	config
	err      error
	builders []*IntegrationUpdateCreate
	conflict []sql.ConflictOption
}

// Save creates the IntegrationUpdate entities in the database.
func (_c *IntegrationUpdateCreateBulk) Save(ctx context.Context) ([]*IntegrationUpdate, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*IntegrationUpdate, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*IntegrationUpdateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *IntegrationUpdateCreateBulk) SaveX(ctx context.Context) []*IntegrationUpdate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IntegrationUpdateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IntegrationUpdateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.IntegrationUpdate.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.IntegrationUpdateUpsert) {
//			SetIntegration(v+v).
//		}).
//		Exec(ctx)
func (_c *IntegrationUpdateCreateBulk) OnConflict(opts ...sql.ConflictOption) *IntegrationUpdateUpsertBulk {
	_c.conflict = opts
	return &IntegrationUpdateUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.IntegrationUpdate.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *IntegrationUpdateCreateBulk) OnConflictColumns(columns ...string) *IntegrationUpdateUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &IntegrationUpdateUpsertBulk{
		create: _c,
	}
}

// IntegrationUpdateUpsertBulk is the builder for "upsert"-ing
// a bulk of IntegrationUpdate nodes.
type IntegrationUpdateUpsertBulk struct {
	create *IntegrationUpdateCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.IntegrationUpdate.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(integrationupdate.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *IntegrationUpdateUpsertBulk) UpdateNewValues() *IntegrationUpdateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(integrationupdate.FieldID)
			}
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(integrationupdate.FieldCreateTime)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.IntegrationUpdate.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *IntegrationUpdateUpsertBulk) Ignore() *IntegrationUpdateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *IntegrationUpdateUpsertBulk) DoNothing() *IntegrationUpdateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the IntegrationUpdateCreateBulk.OnConflict
// documentation for more info.
func (u *IntegrationUpdateUpsertBulk) Update(set func(*IntegrationUpdateUpsert)) *IntegrationUpdateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&IntegrationUpdateUpsert{UpdateSet: update})
	}))
	return u
}

// SetIntegration sets the "integration" field.
func (u *IntegrationUpdateUpsertBulk) SetIntegration(v string) *IntegrationUpdateUpsertBulk {
	return u.Update(func(s *IntegrationUpdateUpsert) {
		s.SetIntegration(v)
	})
}

// UpdateIntegration sets the "integration" field to the value that was provided on create.
func (u *IntegrationUpdateUpsertBulk) UpdateIntegration() *IntegrationUpdateUpsertBulk {
	return u.Update(func(s *IntegrationUpdateUpsert) {
		s.UpdateIntegration()
	})
}

// SetState sets the "state" field.
func (u *IntegrationUpdateUpsertBulk) SetState(v integrationupdate.State) *IntegrationUpdateUpsertBulk {
	return u.Update(func(s *IntegrationUpdateUpsert) {
		s.SetState(v)
	})
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *IntegrationUpdateUpsertBulk) UpdateState() *IntegrationUpdateUpsertBulk {
	return u.Update(func(s *IntegrationUpdateUpsert) {
		s.UpdateState()
	})
}

// SetDetail sets the "detail" field.
func (u *IntegrationUpdateUpsertBulk) SetDetail(v string) *IntegrationUpdateUpsertBulk {
	return u.Update(func(s *IntegrationUpdateUpsert) {
		s.SetDetail(v)
	})
}

// UpdateDetail sets the "detail" field to the value that was provided on create.
func (u *IntegrationUpdateUpsertBulk) UpdateDetail() *IntegrationUpdateUpsertBulk {
	return u.Update(func(s *IntegrationUpdateUpsert) {
		s.UpdateDetail()
	})
}

// ClearDetail clears the value of the "detail" field.
func (u *IntegrationUpdateUpsertBulk) ClearDetail() *IntegrationUpdateUpsertBulk {
	return u.Update(func(s *IntegrationUpdateUpsert) {
		s.ClearDetail()
	})
}

// SetNewVersion sets the "new_version" field.
func (u *IntegrationUpdateUpsertBulk) SetNewVersion(v string) *IntegrationUpdateUpsertBulk {
	return u.Update(func(s *IntegrationUpdateUpsert) {
		s.SetNewVersion(v)
	})
}

// UpdateNewVersion sets the "new_version" field to the value that was provided on create.
func (u *IntegrationUpdateUpsertBulk) UpdateNewVersion() *IntegrationUpdateUpsertBulk {
	return u.Update(func(s *IntegrationUpdateUpsert) {
		s.UpdateNewVersion()
	})
}

// ClearNewVersion clears the value of the "new_version" field.
func (u *IntegrationUpdateUpsertBulk) ClearNewVersion() *IntegrationUpdateUpsertBulk {
	return u.Update(func(s *IntegrationUpdateUpsert) {
		s.ClearNewVersion()
	})
}

// SetRequestedBy sets the "requested_by" field.
func (u *IntegrationUpdateUpsertBulk) SetRequestedBy(v string) *IntegrationUpdateUpsertBulk {
	return u.Update(func(s *IntegrationUpdateUpsert) {
		s.SetRequestedBy(v)
	})
}

// UpdateRequestedBy sets the "requested_by" field to the value that was provided on create.
func (u *IntegrationUpdateUpsertBulk) UpdateRequestedBy() *IntegrationUpdateUpsertBulk {
	return u.Update(func(s *IntegrationUpdateUpsert) {
		s.UpdateRequestedBy()
	})
}

// ClearRequestedBy clears the value of the "requested_by" field.
func (u *IntegrationUpdateUpsertBulk) ClearRequestedBy() *IntegrationUpdateUpsertBulk {
	return u.Update(func(s *IntegrationUpdateUpsert) {
		s.ClearRequestedBy()
	})
}

// SetUpdateTime sets the "update_time" field.
func (u *IntegrationUpdateUpsertBulk) SetUpdateTime(v time.Time) *IntegrationUpdateUpsertBulk {
	return u.Update(func(s *IntegrationUpdateUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *IntegrationUpdateUpsertBulk) UpdateUpdateTime() *IntegrationUpdateUpsertBulk {
	return u.Update(func(s *IntegrationUpdateUpsert) {
		s.UpdateUpdateTime()
	})
}

// Exec executes the query.
func (u *IntegrationUpdateUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the IntegrationUpdateCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for IntegrationUpdateCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *IntegrationUpdateUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
