// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/pdlc-os/fabric/pkg/ent/integrationupdate"
	"github.com/pdlc-os/fabric/pkg/ent/predicate"
)

// IntegrationUpdateUpdate is the builder for updating IntegrationUpdate entities.
type IntegrationUpdateUpdate struct {
	config
	hooks    []Hook
	mutation *IntegrationUpdateMutation
}

// Where appends a list predicates to the IntegrationUpdateUpdate builder.
func (_u *IntegrationUpdateUpdate) Where(ps ...predicate.IntegrationUpdate) *IntegrationUpdateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetIntegration sets the "integration" field.
func (_u *IntegrationUpdateUpdate) SetIntegration(v string) *IntegrationUpdateUpdate {
	_u.mutation.SetIntegration(v)
	return _u
}

// SetNillableIntegration sets the "integration" field if the given value is not nil.
func (_u *IntegrationUpdateUpdate) SetNillableIntegration(v *string) *IntegrationUpdateUpdate {
	if v != nil {
		_u.SetIntegration(*v)
	}
	return _u
}

// SetState sets the "state" field.
func (_u *IntegrationUpdateUpdate) SetState(v integrationupdate.State) *IntegrationUpdateUpdate {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *IntegrationUpdateUpdate) SetNillableState(v *integrationupdate.State) *IntegrationUpdateUpdate {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetDetail sets the "detail" field.
func (_u *IntegrationUpdateUpdate) SetDetail(v string) *IntegrationUpdateUpdate {
	_u.mutation.SetDetail(v)
	return _u
}

// SetNillableDetail sets the "detail" field if the given value is not nil.
func (_u *IntegrationUpdateUpdate) SetNillableDetail(v *string) *IntegrationUpdateUpdate {
	if v != nil {
		_u.SetDetail(*v)
	}
	return _u
}

// ClearDetail clears the value of the "detail" field.
func (_u *IntegrationUpdateUpdate) ClearDetail() *IntegrationUpdateUpdate {
	_u.mutation.ClearDetail()
	return _u
}

// SetNewVersion sets the "new_version" field.
func (_u *IntegrationUpdateUpdate) SetNewVersion(v string) *IntegrationUpdateUpdate {
	_u.mutation.SetNewVersion(v)
	return _u
}

// SetNillableNewVersion sets the "new_version" field if the given value is not nil.
func (_u *IntegrationUpdateUpdate) SetNillableNewVersion(v *string) *IntegrationUpdateUpdate {
	if v != nil {
		_u.SetNewVersion(*v)
	}
	return _u
}

// ClearNewVersion clears the value of the "new_version" field.
func (_u *IntegrationUpdateUpdate) ClearNewVersion() *IntegrationUpdateUpdate {
	_u.mutation.ClearNewVersion()
	return _u
}

// SetRequestedBy sets the "requested_by" field.
func (_u *IntegrationUpdateUpdate) SetRequestedBy(v string) *IntegrationUpdateUpdate {
	_u.mutation.SetRequestedBy(v)
	return _u
}

// SetNillableRequestedBy sets the "requested_by" field if the given value is not nil.
func (_u *IntegrationUpdateUpdate) SetNillableRequestedBy(v *string) *IntegrationUpdateUpdate {
	if v != nil {
		_u.SetRequestedBy(*v)
	}
	return _u
}

// ClearRequestedBy clears the value of the "requested_by" field.
func (_u *IntegrationUpdateUpdate) ClearRequestedBy() *IntegrationUpdateUpdate {
	_u.mutation.ClearRequestedBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *IntegrationUpdateUpdate) SetUpdateTime(v time.Time) *IntegrationUpdateUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// Mutation returns the IntegrationUpdateMutation object of the builder.
func (_u *IntegrationUpdateUpdate) Mutation() *IntegrationUpdateMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *IntegrationUpdateUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IntegrationUpdateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *IntegrationUpdateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IntegrationUpdateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *IntegrationUpdateUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := integrationupdate.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *IntegrationUpdateUpdate) check() error {
	if v, ok := _u.mutation.Integration(); ok {
		if err := integrationupdate.IntegrationValidator(v); err != nil {
			return &ValidationError{Name: "integration", err: fmt.Errorf(`ent: validator failed for field "IntegrationUpdate.integration": %w`, err)}
		}
	}
	if v, ok := _u.mutation.State(); ok {
		if err := integrationupdate.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "IntegrationUpdate.state": %w`, err)}
		}
	}
	return nil
}

func (_u *IntegrationUpdateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(integrationupdate.Table, integrationupdate.Columns, sqlgraph.NewFieldSpec(integrationupdate.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Integration(); ok {
		_spec.SetField(integrationupdate.FieldIntegration, field.TypeString, value)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(integrationupdate.FieldState, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Detail(); ok {
		_spec.SetField(integrationupdate.FieldDetail, field.TypeString, value)
	}
	if _u.mutation.DetailCleared() {
		_spec.ClearField(integrationupdate.FieldDetail, field.TypeString)
	}
	if value, ok := _u.mutation.NewVersion(); ok {
		_spec.SetField(integrationupdate.FieldNewVersion, field.TypeString, value)
	}
	if _u.mutation.NewVersionCleared() {
		_spec.ClearField(integrationupdate.FieldNewVersion, field.TypeString)
	}
	if value, ok := _u.mutation.RequestedBy(); ok {
		_spec.SetField(integrationupdate.FieldRequestedBy, field.TypeString, value)
	}
	if _u.mutation.RequestedByCleared() {
		_spec.ClearField(integrationupdate.FieldRequestedBy, field.TypeString)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(integrationupdate.FieldUpdateTime, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{integrationupdate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// IntegrationUpdateUpdateOne is the builder for updating a single IntegrationUpdate entity.
type IntegrationUpdateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *IntegrationUpdateMutation
}

// SetIntegration sets the "integration" field.
func (_u *IntegrationUpdateUpdateOne) SetIntegration(v string) *IntegrationUpdateUpdateOne {
	_u.mutation.SetIntegration(v)
	return _u
}

// SetNillableIntegration sets the "integration" field if the given value is not nil.
func (_u *IntegrationUpdateUpdateOne) SetNillableIntegration(v *string) *IntegrationUpdateUpdateOne {
	if v != nil {
		_u.SetIntegration(*v)
	}
	return _u
}

// SetState sets the "state" field.
func (_u *IntegrationUpdateUpdateOne) SetState(v integrationupdate.State) *IntegrationUpdateUpdateOne {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *IntegrationUpdateUpdateOne) SetNillableState(v *integrationupdate.State) *IntegrationUpdateUpdateOne {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetDetail sets the "detail" field.
func (_u *IntegrationUpdateUpdateOne) SetDetail(v string) *IntegrationUpdateUpdateOne {
	_u.mutation.SetDetail(v)
	return _u
}

// SetNillableDetail sets the "detail" field if the given value is not nil.
func (_u *IntegrationUpdateUpdateOne) SetNillableDetail(v *string) *IntegrationUpdateUpdateOne {
	if v != nil {
		_u.SetDetail(*v)
	}
	return _u
}

// ClearDetail clears the value of the "detail" field.
func (_u *IntegrationUpdateUpdateOne) ClearDetail() *IntegrationUpdateUpdateOne {
	_u.mutation.ClearDetail()
	return _u
}

// SetNewVersion sets the "new_version" field.
func (_u *IntegrationUpdateUpdateOne) SetNewVersion(v string) *IntegrationUpdateUpdateOne {
	_u.mutation.SetNewVersion(v)
	return _u
}

// SetNillableNewVersion sets the "new_version" field if the given value is not nil.
func (_u *IntegrationUpdateUpdateOne) SetNillableNewVersion(v *string) *IntegrationUpdateUpdateOne {
	if v != nil {
		_u.SetNewVersion(*v)
	}
	return _u
}

// ClearNewVersion clears the value of the "new_version" field.
func (_u *IntegrationUpdateUpdateOne) ClearNewVersion() *IntegrationUpdateUpdateOne {
	_u.mutation.ClearNewVersion()
	return _u
}

// SetRequestedBy sets the "requested_by" field.
func (_u *IntegrationUpdateUpdateOne) SetRequestedBy(v string) *IntegrationUpdateUpdateOne {
	_u.mutation.SetRequestedBy(v)
	return _u
}

// SetNillableRequestedBy sets the "requested_by" field if the given value is not nil.
func (_u *IntegrationUpdateUpdateOne) SetNillableRequestedBy(v *string) *IntegrationUpdateUpdateOne {
	if v != nil {
		_u.SetRequestedBy(*v)
	}
	return _u
}

// ClearRequestedBy clears the value of the "requested_by" field.
func (_u *IntegrationUpdateUpdateOne) ClearRequestedBy() *IntegrationUpdateUpdateOne {
	_u.mutation.ClearRequestedBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *IntegrationUpdateUpdateOne) SetUpdateTime(v time.Time) *IntegrationUpdateUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// Mutation returns the IntegrationUpdateMutation object of the builder.
func (_u *IntegrationUpdateUpdateOne) Mutation() *IntegrationUpdateMutation {
	return _u.mutation
}

// Where appends a list predicates to the IntegrationUpdateUpdate builder.
func (_u *IntegrationUpdateUpdateOne) Where(ps ...predicate.IntegrationUpdate) *IntegrationUpdateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *IntegrationUpdateUpdateOne) Select(field string, fields ...string) *IntegrationUpdateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated IntegrationUpdate entity.
func (_u *IntegrationUpdateUpdateOne) Save(ctx context.Context) (*IntegrationUpdate, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IntegrationUpdateUpdateOne) SaveX(ctx context.Context) *IntegrationUpdate {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *IntegrationUpdateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IntegrationUpdateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *IntegrationUpdateUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := integrationupdate.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *IntegrationUpdateUpdateOne) check() error {
	if v, ok := _u.mutation.Integration(); ok {
		if err := integrationupdate.IntegrationValidator(v); err != nil {
			return &ValidationError{Name: "integration", err: fmt.Errorf(`ent: validator failed for field "IntegrationUpdate.integration": %w`, err)}
		}
	}
	if v, ok := _u.mutation.State(); ok {
		if err := integrationupdate.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "IntegrationUpdate.state": %w`, err)}
		}
	}
	return nil
}

func (_u *IntegrationUpdateUpdateOne) sqlSave(ctx context.Context) (_node *IntegrationUpdate, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(integrationupdate.Table, integrationupdate.Columns, sqlgraph.NewFieldSpec(integrationupdate.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "IntegrationUpdate.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, integrationupdate.FieldID)
		for _, f := range fields {
			if !integrationupdate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != integrationupdate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Integration(); ok {
		_spec.SetField(integrationupdate.FieldIntegration, field.TypeString, value)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(integrationupdate.FieldState, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Detail(); ok {
		_spec.SetField(integrationupdate.FieldDetail, field.TypeString, value)
	}
	if _u.mutation.DetailCleared() {
		_spec.ClearField(integrationupdate.FieldDetail, field.TypeString)
	}
	if value, ok := _u.mutation.NewVersion(); ok {
		_spec.SetField(integrationupdate.FieldNewVersion, field.TypeString, value)
	}
	if _u.mutation.NewVersionCleared() {
		_spec.ClearField(integrationupdate.FieldNewVersion, field.TypeString)
	}
	if value, ok := _u.mutation.RequestedBy(); ok {
		_spec.SetField(integrationupdate.FieldRequestedBy, field.TypeString, value)
	}
	if _u.mutation.RequestedByCleared() {
		_spec.ClearField(integrationupdate.FieldRequestedBy, field.TypeString)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(integrationupdate.FieldUpdateTime, field.TypeTime, value)
	}
	_node = &IntegrationUpdate{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{integrationupdate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
