// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/pdlc-os/fabric/pkg/ent/integrationconfig"
	"github.com/pdlc-os/fabric/pkg/ent/predicate"
)

// IntegrationConfigUpdate is the builder for updating IntegrationConfig entities.
type IntegrationConfigUpdate struct {
	config
	hooks    []Hook
	mutation *IntegrationConfigMutation
}

// Where appends a list predicates to the IntegrationConfigUpdate builder.
func (_u *IntegrationConfigUpdate) Where(ps ...predicate.IntegrationConfig) *IntegrationConfigUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetIntegration sets the "integration" field.
func (_u *IntegrationConfigUpdate) SetIntegration(v string) *IntegrationConfigUpdate {
	_u.mutation.SetIntegration(v)
	return _u
}

// SetNillableIntegration sets the "integration" field if the given value is not nil.
func (_u *IntegrationConfigUpdate) SetNillableIntegration(v *string) *IntegrationConfigUpdate {
	if v != nil {
		_u.SetIntegration(*v)
	}
	return _u
}

// SetConfig sets the "config" field.
func (_u *IntegrationConfigUpdate) SetConfig(v string) *IntegrationConfigUpdate {
	_u.mutation.SetConfig(v)
	return _u
}

// SetNillableConfig sets the "config" field if the given value is not nil.
func (_u *IntegrationConfigUpdate) SetNillableConfig(v *string) *IntegrationConfigUpdate {
	if v != nil {
		_u.SetConfig(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *IntegrationConfigUpdate) SetEnabled(v bool) *IntegrationConfigUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *IntegrationConfigUpdate) SetNillableEnabled(v *bool) *IntegrationConfigUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *IntegrationConfigUpdate) SetUpdatedBy(v string) *IntegrationConfigUpdate {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *IntegrationConfigUpdate) SetNillableUpdatedBy(v *string) *IntegrationConfigUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *IntegrationConfigUpdate) ClearUpdatedBy() *IntegrationConfigUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *IntegrationConfigUpdate) SetUpdateTime(v time.Time) *IntegrationConfigUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// Mutation returns the IntegrationConfigMutation object of the builder.
func (_u *IntegrationConfigUpdate) Mutation() *IntegrationConfigMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *IntegrationConfigUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IntegrationConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *IntegrationConfigUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IntegrationConfigUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *IntegrationConfigUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := integrationconfig.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *IntegrationConfigUpdate) check() error {
	if v, ok := _u.mutation.Integration(); ok {
		if err := integrationconfig.IntegrationValidator(v); err != nil {
			return &ValidationError{Name: "integration", err: fmt.Errorf(`ent: validator failed for field "IntegrationConfig.integration": %w`, err)}
		}
	}
	return nil
}

func (_u *IntegrationConfigUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(integrationconfig.Table, integrationconfig.Columns, sqlgraph.NewFieldSpec(integrationconfig.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Integration(); ok {
		_spec.SetField(integrationconfig.FieldIntegration, field.TypeString, value)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(integrationconfig.FieldConfig, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(integrationconfig.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(integrationconfig.FieldUpdatedBy, field.TypeString, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(integrationconfig.FieldUpdatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(integrationconfig.FieldUpdateTime, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{integrationconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// IntegrationConfigUpdateOne is the builder for updating a single IntegrationConfig entity.
type IntegrationConfigUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *IntegrationConfigMutation
}

// SetIntegration sets the "integration" field.
func (_u *IntegrationConfigUpdateOne) SetIntegration(v string) *IntegrationConfigUpdateOne {
	_u.mutation.SetIntegration(v)
	return _u
}

// SetNillableIntegration sets the "integration" field if the given value is not nil.
func (_u *IntegrationConfigUpdateOne) SetNillableIntegration(v *string) *IntegrationConfigUpdateOne {
	if v != nil {
		_u.SetIntegration(*v)
	}
	return _u
}

// SetConfig sets the "config" field.
func (_u *IntegrationConfigUpdateOne) SetConfig(v string) *IntegrationConfigUpdateOne {
	_u.mutation.SetConfig(v)
	return _u
}

// SetNillableConfig sets the "config" field if the given value is not nil.
func (_u *IntegrationConfigUpdateOne) SetNillableConfig(v *string) *IntegrationConfigUpdateOne {
	if v != nil {
		_u.SetConfig(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *IntegrationConfigUpdateOne) SetEnabled(v bool) *IntegrationConfigUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *IntegrationConfigUpdateOne) SetNillableEnabled(v *bool) *IntegrationConfigUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *IntegrationConfigUpdateOne) SetUpdatedBy(v string) *IntegrationConfigUpdateOne {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *IntegrationConfigUpdateOne) SetNillableUpdatedBy(v *string) *IntegrationConfigUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *IntegrationConfigUpdateOne) ClearUpdatedBy() *IntegrationConfigUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *IntegrationConfigUpdateOne) SetUpdateTime(v time.Time) *IntegrationConfigUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// Mutation returns the IntegrationConfigMutation object of the builder.
func (_u *IntegrationConfigUpdateOne) Mutation() *IntegrationConfigMutation {
	return _u.mutation
}

// Where appends a list predicates to the IntegrationConfigUpdate builder.
func (_u *IntegrationConfigUpdateOne) Where(ps ...predicate.IntegrationConfig) *IntegrationConfigUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *IntegrationConfigUpdateOne) Select(field string, fields ...string) *IntegrationConfigUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated IntegrationConfig entity.
func (_u *IntegrationConfigUpdateOne) Save(ctx context.Context) (*IntegrationConfig, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IntegrationConfigUpdateOne) SaveX(ctx context.Context) *IntegrationConfig {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *IntegrationConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IntegrationConfigUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *IntegrationConfigUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := integrationconfig.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *IntegrationConfigUpdateOne) check() error {
	if v, ok := _u.mutation.Integration(); ok {
		if err := integrationconfig.IntegrationValidator(v); err != nil {
			return &ValidationError{Name: "integration", err: fmt.Errorf(`ent: validator failed for field "IntegrationConfig.integration": %w`, err)}
		}
	}
	return nil
}

func (_u *IntegrationConfigUpdateOne) sqlSave(ctx context.Context) (_node *IntegrationConfig, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(integrationconfig.Table, integrationconfig.Columns, sqlgraph.NewFieldSpec(integrationconfig.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "IntegrationConfig.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, integrationconfig.FieldID)
		for _, f := range fields {
			if !integrationconfig.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != integrationconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Integration(); ok {
		_spec.SetField(integrationconfig.FieldIntegration, field.TypeString, value)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(integrationconfig.FieldConfig, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(integrationconfig.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(integrationconfig.FieldUpdatedBy, field.TypeString, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(integrationconfig.FieldUpdatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(integrationconfig.FieldUpdateTime, field.TypeTime, value)
	}
	_node = &IntegrationConfig{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{integrationconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
