// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/pdlc-os/fabric/pkg/ent/integrationconfig"
	"github.com/pdlc-os/fabric/pkg/ent/predicate"
)

// IntegrationConfigDelete is the builder for deleting a IntegrationConfig entity.
type IntegrationConfigDelete struct {
	config
	hooks    []Hook
	mutation *IntegrationConfigMutation
}

// Where appends a list predicates to the IntegrationConfigDelete builder.
func (_d *IntegrationConfigDelete) Where(ps ...predicate.IntegrationConfig) *IntegrationConfigDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *IntegrationConfigDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *IntegrationConfigDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *IntegrationConfigDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(integrationconfig.Table, sqlgraph.NewFieldSpec(integrationconfig.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// IntegrationConfigDeleteOne is the builder for deleting a single IntegrationConfig entity.
type IntegrationConfigDeleteOne struct {
	_d *IntegrationConfigDelete
}

// Where appends a list predicates to the IntegrationConfigDelete builder.
func (_d *IntegrationConfigDeleteOne) Where(ps ...predicate.IntegrationConfig) *IntegrationConfigDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *IntegrationConfigDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{integrationconfig.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *IntegrationConfigDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
