apiVersion: v1
kind: Namespace
metadata:
  name: fabric-agents
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fabric-workspaces
spec:
  capacity:
    storage: 1Ti
  accessModes: [ReadWriteMany]
  nfs:
    server: 10.45.255.170
    path: /fabric_share
  mountOptions: [vers=3, hard, nconnect=4]
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fabric-workspaces
  namespace: fabric-agents
spec:
  accessModes: [ReadWriteMany]
  storageClassName: ""
  volumeName: fabric-workspaces
  resources:
    requests:
      storage: 1Ti
