// Code generated by ent, DO NOT EDIT.

package discordpendinglink

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/pdlc-os/fabric/pkg/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldLTE(FieldID, id))
}

// Code applies equality check predicate on the "code" field. It's identical to CodeEQ.
func Code(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldEQ(FieldCode, v))
}

// DiscordUserID applies equality check predicate on the "discord_user_id" field. It's identical to DiscordUserIDEQ.
func DiscordUserID(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldEQ(FieldDiscordUserID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldEQ(FieldStatus, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldEQ(FieldUserID, v))
}

// UserEmail applies equality check predicate on the "user_email" field. It's identical to UserEmailEQ.
func UserEmail(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldEQ(FieldUserEmail, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldEQ(FieldExpiresAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldEQ(FieldCreatedAt, v))
}

// CodeEQ applies the EQ predicate on the "code" field.
func CodeEQ(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldEQ(FieldCode, v))
}

// CodeNEQ applies the NEQ predicate on the "code" field.
func CodeNEQ(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldNEQ(FieldCode, v))
}

// CodeIn applies the In predicate on the "code" field.
func CodeIn(vs ...string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldIn(FieldCode, vs...))
}

// CodeNotIn applies the NotIn predicate on the "code" field.
func CodeNotIn(vs ...string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldNotIn(FieldCode, vs...))
}

// CodeGT applies the GT predicate on the "code" field.
func CodeGT(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldGT(FieldCode, v))
}

// CodeGTE applies the GTE predicate on the "code" field.
func CodeGTE(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldGTE(FieldCode, v))
}

// CodeLT applies the LT predicate on the "code" field.
func CodeLT(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldLT(FieldCode, v))
}

// CodeLTE applies the LTE predicate on the "code" field.
func CodeLTE(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldLTE(FieldCode, v))
}

// CodeContains applies the Contains predicate on the "code" field.
func CodeContains(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldContains(FieldCode, v))
}

// CodeHasPrefix applies the HasPrefix predicate on the "code" field.
func CodeHasPrefix(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldHasPrefix(FieldCode, v))
}

// CodeHasSuffix applies the HasSuffix predicate on the "code" field.
func CodeHasSuffix(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldHasSuffix(FieldCode, v))
}

// CodeEqualFold applies the EqualFold predicate on the "code" field.
func CodeEqualFold(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldEqualFold(FieldCode, v))
}

// CodeContainsFold applies the ContainsFold predicate on the "code" field.
func CodeContainsFold(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldContainsFold(FieldCode, v))
}

// DiscordUserIDEQ applies the EQ predicate on the "discord_user_id" field.
func DiscordUserIDEQ(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldEQ(FieldDiscordUserID, v))
}

// DiscordUserIDNEQ applies the NEQ predicate on the "discord_user_id" field.
func DiscordUserIDNEQ(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldNEQ(FieldDiscordUserID, v))
}

// DiscordUserIDIn applies the In predicate on the "discord_user_id" field.
func DiscordUserIDIn(vs ...string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldIn(FieldDiscordUserID, vs...))
}

// DiscordUserIDNotIn applies the NotIn predicate on the "discord_user_id" field.
func DiscordUserIDNotIn(vs ...string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldNotIn(FieldDiscordUserID, vs...))
}

// DiscordUserIDGT applies the GT predicate on the "discord_user_id" field.
func DiscordUserIDGT(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldGT(FieldDiscordUserID, v))
}

// DiscordUserIDGTE applies the GTE predicate on the "discord_user_id" field.
func DiscordUserIDGTE(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldGTE(FieldDiscordUserID, v))
}

// DiscordUserIDLT applies the LT predicate on the "discord_user_id" field.
func DiscordUserIDLT(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldLT(FieldDiscordUserID, v))
}

// DiscordUserIDLTE applies the LTE predicate on the "discord_user_id" field.
func DiscordUserIDLTE(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldLTE(FieldDiscordUserID, v))
}

// DiscordUserIDContains applies the Contains predicate on the "discord_user_id" field.
func DiscordUserIDContains(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldContains(FieldDiscordUserID, v))
}

// DiscordUserIDHasPrefix applies the HasPrefix predicate on the "discord_user_id" field.
func DiscordUserIDHasPrefix(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldHasPrefix(FieldDiscordUserID, v))
}

// DiscordUserIDHasSuffix applies the HasSuffix predicate on the "discord_user_id" field.
func DiscordUserIDHasSuffix(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldHasSuffix(FieldDiscordUserID, v))
}

// DiscordUserIDEqualFold applies the EqualFold predicate on the "discord_user_id" field.
func DiscordUserIDEqualFold(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldEqualFold(FieldDiscordUserID, v))
}

// DiscordUserIDContainsFold applies the ContainsFold predicate on the "discord_user_id" field.
func DiscordUserIDContainsFold(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldContainsFold(FieldDiscordUserID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldContainsFold(FieldStatus, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldContainsFold(FieldUserID, v))
}

// UserEmailEQ applies the EQ predicate on the "user_email" field.
func UserEmailEQ(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldEQ(FieldUserEmail, v))
}

// UserEmailNEQ applies the NEQ predicate on the "user_email" field.
func UserEmailNEQ(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldNEQ(FieldUserEmail, v))
}

// UserEmailIn applies the In predicate on the "user_email" field.
func UserEmailIn(vs ...string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldIn(FieldUserEmail, vs...))
}

// UserEmailNotIn applies the NotIn predicate on the "user_email" field.
func UserEmailNotIn(vs ...string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldNotIn(FieldUserEmail, vs...))
}

// UserEmailGT applies the GT predicate on the "user_email" field.
func UserEmailGT(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldGT(FieldUserEmail, v))
}

// UserEmailGTE applies the GTE predicate on the "user_email" field.
func UserEmailGTE(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldGTE(FieldUserEmail, v))
}

// UserEmailLT applies the LT predicate on the "user_email" field.
func UserEmailLT(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldLT(FieldUserEmail, v))
}

// UserEmailLTE applies the LTE predicate on the "user_email" field.
func UserEmailLTE(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldLTE(FieldUserEmail, v))
}

// UserEmailContains applies the Contains predicate on the "user_email" field.
func UserEmailContains(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldContains(FieldUserEmail, v))
}

// UserEmailHasPrefix applies the HasPrefix predicate on the "user_email" field.
func UserEmailHasPrefix(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldHasPrefix(FieldUserEmail, v))
}

// UserEmailHasSuffix applies the HasSuffix predicate on the "user_email" field.
func UserEmailHasSuffix(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldHasSuffix(FieldUserEmail, v))
}

// UserEmailEqualFold applies the EqualFold predicate on the "user_email" field.
func UserEmailEqualFold(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldEqualFold(FieldUserEmail, v))
}

// UserEmailContainsFold applies the ContainsFold predicate on the "user_email" field.
func UserEmailContainsFold(v string) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldContainsFold(FieldUserEmail, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldLTE(FieldExpiresAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DiscordPendingLink) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DiscordPendingLink) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DiscordPendingLink) predicate.DiscordPendingLink {
	return predicate.DiscordPendingLink(sql.NotPredicates(p))
}
